README.md
- resolves electrode-io/electrode-io.github.io/#89.
=> cleanup. corrected names and # fragments

client/components/home.jsx
Was seeing some issues in the logs on the dev environment.
```
Warning: Failed prop type: Invalid prop `data` of type `string` supplied to `HomeWrapper`, expected `object`.
in HomeWrapper (created by Connect(HomeWrapper))
in Connect(HomeWrapper) (created by RouterContext)
in RouterContext
in Provider
Warning: Failed prop type: Invalid prop `data` of type `string` supplied to `Home`, expected `object`.
in Home (created by HomeWrapper)
in HomeWrapper (created by Connect(HomeWrapper))
in Connect(HomeWrapper) (created by RouterContext)
in RouterContext
in Provider
```
The initial server state here (https://github.com/electrode-io/electrode-boilerplate-universal-react-node/blob/506906c8a64d8047bb56ba9a4ac77ef95038572b/server/views/index-view.jsx#L14) is a string not an object. So updating the …
=> Fix proptype from object to string

README.md, client/app.jsx, client/devtools/devtools.dev.js, client/devtools/devtools.prod.js, client/devtools/index.js, package.json
**Summary:**
Integrating Redux devtools with the Electrode sample app to allow users to easily debug their application issues. There is not much data in the store given it is a sample application, but it will serve as a reference on integrating devtools with the Electrode app.
**Screenshot:**
=> Add support for Devtools

client/components/home.jsx, client/entry.config.js, client/styles/base.css, server/index.js, server/plugins/webapp/index.html, server/plugins/webapp/index.js
Moves some inline styles to external files to demonstrate critical CSS inlining. Adds a new marker to `webapp` that injects a style tag with the parsed critical css.
=> Implement critical CSS injection

samples/universal-react-node/package.json
We are importing `react-toast-dep` but it isn't a dependency. https://github.com/electrode-io/electrode/blob/master/samples/universal-react-node/client/components/home.jsx#L4 
@ananavati @donsalari
=> Add react-toast-dep

packages/electrode-archetype-react-component/config/webpack/webpack.config.test.js
When running "gulp check" on a Windows machine, it would fail to run tests with issues related to Sinon and Webpack. The included module.noParse regex would only work on a Linux based machine, this commit allows Windows support
=> Fix for gulp check on Windows

packages/electrode-redux-router-engine/README.md, packages/electrode-redux-router-engine/lib/redux-router-engine.js, packages/generator-electrode/generators/app/templates/client/components/home.jsx
[Issue 16](https://github.com/electrode-io/electrode-server/issues/16) and [Issue 34](https://github.com/electrode-io/electrode/issues/34)
Errors inside index-view.js promises silently failed. logging errors for stack trace.
```
ReferenceError: i_am_undefined is not defined
at ReduxRouterEngine.createReduxStore (/Users/a0k00e3/Desktop/errors/server/views/index-view.js:18:3)
at ReduxRouterEngine._handleRender (/Users/a0k00e3/Desktop/errors/node_modules/electrode-redux-router-engine/lib/redux-router-engine.js:96:72)
at _matchRoute.then (/Users/a0k00e3/Desktop/errors/node_modules/electrode-redux-router-engine/lib/redux-router-engine.js:60:23)
at bound (domain.js:280:14)
at runBound (domain.js:293:12)
at tryCatcher (/Users/a0k00e3/Desktop/errors/node_modules/bluebird/js/release/util.js:16:23) …
```
=> Display errors in ReduxStore

samples/universal-material-ui/server/plugins/webapp/index.js
Change the webapp to point to the correct bundle.  Maybe core electrode server was updated to make a main bundle and this app was not fixed.
=> Material example is not referencing the main bundle

packages/generator-electrode/generators/app/templates/server/express-server.js
Looks like the generator is not passing through the userConfigs from the calling of the server to loadConfigs.  loadConfigs signature takes in userConfigs, but as it is right now always gets an empty config object.  The entry point for the module is passed the userConfigs, so this pull is just actually getting it to the loadConfigs method, via the Promise.resolve.
=> Pass userConfig to loadConfigs

packages/electrode-archetype-react-app/config/webpack/partial/extract.js
Based on a discussion with @ananavati in https://gitter.im/electrode-io/electrode.
~I think the [Develop Styles](http://www.electrode.io/docs/develop_styles.html) documentation should also be updated by this PR to reflect this change, but I don't see it in this repository.~ Done: electrode-io/electrode-io.github.io#377
Note: This is a non-breaking change. In sufficiently large/deep applications, this could potentially have a performance impact since it traverses all paths of the `client` directory. The impact is likely negligible though.
=> Update Extract partial to use unopinionated glob

packages/electrode-react-webapp/lib/express/index.js, packages/electrode-react-webapp/lib/hapi/index.js, packages/electrode-react-webapp/lib/koa/index.js
This change lets users configure an optional `methods` attribute for `electrode-react-webapp` paths. This lets me render `POST` requests on server.
"webapp": {
"module": "electrode-react-webapp/lib/hapi",
"options": {
"pageTitle": "title",
"paths": {
"/{args*}": {
"method": ["GET", "POST"],
"content": {
"module": "./server/views/index-view"
}
}
}
}
}
This needs a Koa implementation, and I have not tested the Express implementation. Works for Hapi.
=> Allow non-GET methods on electrode-react-webapp routes

packages/electrode-archetype-react-app-dev/config/webpack/partial/babel.js, packages/electrode-archetype-react-app-dev/config/webpack/partial/hot.js, packages/electrode-archetype-react-app-dev/config/webpack/webpack.config.hot.js, packages/electrode-archetype-react-app/arch-gulpfile.js, packages/generator-electrode/generators/app/templates/src/client/app.jsx, packages/generator-electrode/generators/app/templates/src/client/components/home.jsx, samples/universal-react-node/client/app.jsx
=> archetype-react-app: Fix webpack-dev-server HMR

packages/electrode-archetype-react-app-dev/config/webpack/base.js, packages/electrode-archetype-react-app-dev/config/webpack/partial/extract.js, packages/electrode-archetype-react-app/config/archetype.js
@jchip @ananavati @aweary 
This PR adds the ability for an app to use both stylus and css modules together. While adding in this feature, I found that there is no reliable way to detect that both css modules and stylus should be used (since a project could contain only stylus files but still want to use css modules), so I have added in reading from a `config/css-config` file. I believe we can also utilize the same config file to allow options like a custom `generatedScopeName`.
=> Stylus and css modules together

packages/electrode-archetype-react-app/arch-gulpfile.js, packages/electrode-archetype-react-app/config/archetype.js, packages/electrode-react-webapp/lib/react-webapp.js
This makes it so WEBPACK_HOST and WEBPACK_DEV_PORT are passed to the applicable parts of the application when starting up using `gulp dev`. Without this, it defaults to localhost and 2992 making it impossible to develop unless the developer has access to the local machine.
This is related to https://github.com/electrode-io/electrode/issues/154
=> Pass webpack-dev host and port

packages/electrode-archetype-react-app/arch-gulpfile.js
The DLL plugin can be used to create client side DLL bundles in the app. 
In the `universal-react-node` application, I have added a `dll.config.js` file.
```js
module.exports = {
components: [
"isomorphic-fetch"
],
vendor1: [
"lodash",
"react",
"react-dom"
],
vendor2: [
"redux"
]
};
```
During the `gulp build` task I am now able to see the following bundles and their respective maps.
=> re-enable dll tasks

packages/electrode-archetype-react-app-dev/config/webpack/partial/babel.js
@ananavati @aweary @donsalari @jchip 
This PR allows for extending our babel loader as needed. Different projects may need different `excludes`, `query`, or other options, so I think it makes sense to be able to update those values given by a config. The `extendBabelLoader` config will live in `archetype/config.js` under the `webpack` key for projects that need it.
=> Babel extend

packages/electrode-react-webapp/lib/react-webapp.js, packages/electrode-react-webapp/test/spec/index.spec.js
@jchip 
I'm not sure why the manifest was set up to load from the dev server in dev mode, but I've confirmed this fixes the issue.
=> Load manifest in dev mode

packages/electrode-archetype-react-app-dev/config/webpack/webpack.config.dll.js
The config for the DLL plugin needs the DLL bundles as entries, so clearing the entry value before merging.
=> fix DLL plugin

packages/generator-electrode-component/app/templates/editorconfig
**Context:**
The generator-electrode-component was enforcing tabbed indents over spaces, while the eslint configuration is set up to check for 2-space tabs.  The changes to the file make the editorconfig consistent with eslint rules and with the editorconfig found in the generator-electrode project.
**Solution:**
- Switched to 2 space indents
- Removed unnecessary json rules 
- Added md rule
=> generator-electrode-component: modify editorconfig for consistency with linting rules

packages/electrode-archetype-react-component/config/webpack/webpack.config.test.js
Reverts electrode-io/electrode#159
This seems to be causing tests to hang when running `npm test`
=> Revert "#158: modify webpack test config to allow for correct relative paths"

packages/electrode-archetype-react-app/arch-gulpfile.js
The wds.* commands do not return.  Rather than force a return through backgrounding and have the problem of terminating after user terminates the parent task, just run the wds.test and watch command in parallel.  All other occurrences of wds.* commands are in parallel.
=> archetype-react-app: run webpack and test watch in parallel (#102)

packages/electrode-archetype-react-component/config/webpack/webpack.config.js
The changes on (https://github.com/electrode-io/electrode/pull/211) had a "remnant" import which caused a error during webpack build.
=> bug-fix for stylus+ css-modules support

packages/electrode-archetype-react-app-dev/config/karma/karma.conf.js
The `karma-intl-shim` is already imported into the electrode-archetype-react-app-dev package, but not actually applied to the Karma config. 
If there's a way to configure this from my project, I'd love to know, but as it stands it looks like the karma config isn't configurable unless I write a new gulp task. Is that correct?
For easy searching, Here's the error that I received from PhantomJS when I tried to run tests with localized components: `Invariant Violation: [React Intl] The `Intl` APIs must be available in the runtime, and do not appear to be built-in. An `Intl` polyfill should be loaded.`
=> Add karma-intl-shim to the karma config of electrode-archetype-react-app-dev

packages/electrode-archetype-react-app-dev/config/webpack/partial/extract-style.js
Closes electrode-io/electrode#190
---
Followup to electrode-io/electrode#253
=> archetype-react-app-dev: fix CSS modules class name

packages/generator-electrode/generators/app/index.js, packages/generator-electrode/generators/config/index.js, packages/generator-electrode/generators/git/index.js, packages/generator-electrode/generators/webapp/index.js
Accepts and checks for parameters for a `gitHubUrl` and a flag `isExtended` and `serverType`.
The generator that is using the electrode-OSS generator can now pass these values to the OSS generator.
The `githubUrl` will override the repo url for `package.json` and the .`git`.
`serverType` with set the props and will hide the prompt asking for the server type. This helps control the kind of server you want to use in your project.
`isExtended` is currently only used to delay the dependency installation and we transfer control back to the calling generator to complete the installation.
=> Accept Parameters to check if the Generator has been extended

packages/electrode-archetype-react-app-dev/config/webpack/partial/extract-style.js
**Context**
The `cssModuleSupport` should be false if only stylus files exist, and should be true if only css files exist.  Currently the extract-style partial works in reverse, adding rules for loading stylus when there are only css files and not adding rules for loading stylus when there are only stylus files.  This is the logic from `electrode-archetype-react-app-dev@1.10.0`
```js
if (stylusExists && !cssNextExists) {
cssModuleSupport = false;
}
```
**Solution**
Invert the logic for cssModuleSupport variable to return the partial to intended functionality.
=> invert cssModuleSupport so that it chooses the correct loaders

packages/electrode-archetype-react-app-dev/config/webpack/partial/dev.js, packages/electrode-react-webapp/lib/react-webapp.js
In our development environment we need to run the webpack asset server with HTTPS.
Would you be open to accepting a pull request to allow this to be configured in Electrode?
Run in https mode like this:
```sh
WEBPACK_DEV_HTTPS=true npm start
```
or add to your `package.json`:
```json
{
"scripts": {
"start": "if test \"$NODE_ENV\" = \"production\"; then npm run prod; else WEBPACK_DEV_HTTPS=true gulp dev; fi"
}
}
```
cc @FreaKzero
=> Add environment variable for webpack dev HTTPS

packages/electrode-webpack-reporter/lib/webpack-reporter.js
It looks like this was a recent unintentional omission.  Without this fix `gulp dev` on a freshly created app is giving me:
```
[ 'TypeError: Cannot read property \'socketPort\' of undefined',
'    at new WebpackReporter (/Users/johnmclaughlin/git/rcel/node_modules/electrode-webpack-reporter/lib/webpack-reporter.js:44:45)',
'    at module.exports.options (/Users/johnmclaughlin/git/rcel/node_modules/electrode-archetype-react-app-dev/config/webpack/partial/html-reporter.js:8:22)',
'    at /Users/johnmclaughlin/git/rcel/node_modules/webpack-config-composer/lib/index.js:105:17',
'    at Array.forEach (native)',
'    at WebpackConfigComposer.compose (/Users/johnmclaughlin/git/rcel/node_modules/webpack-config-composer/lib/index.js:94:16)',
'    at compose …
```
=> Use socketPort from defaults

packages/electrode-archetype-react-app-dev/config/webpack/partial/extract-style.js, packages/electrode-archetype-react-app/support/index.js, packages/generator-electrode/generators/app/templates/_package.json
The production build uses the `lib` folder for built assets. Because CSS
Modules uses the file path to generate the unique hash for the class names,
this causes an inconsistency between the client and server class names, which
causes a Flash Of Unstyled Content (FOUC) in production mode.
cc @karlhorky
=> Fix CSS Modules FOUC with production build

packages/electrode-archetype-react-app-dev/config/webpack/partial/test-base.js, packages/electrode-archetype-react-app/arch-gulpfile.js
**Tested on Windows 10 and Mac OS10.12.4**
**Context**
Cannot run `npm test` on Electrode apps on Windows devices without these to errors:
1. #92 Istanbul coverage failing on windows
2. #80 Was applied to the component archetype but not the app archetype
**Fixes**
1. Fix windows coverage errors #92 with solution https://github.com/gotwarlost/istanbul/issues/90
2. Determine regex value based on whether the device platform is Windows. (#82)
**I would really like to apply this fix to the newest 1.x version because we are currently using 1.10.0 in production and can't run our tests on any Windows devices.  We can't update to 2.x yet because there are quite a few known bugs.  Should 1.* updates be made to the webpack-1.0 branch?*
=> Fix Windows coverage errors and Windows Sinon error

packages/electrode-archetype-react-app-dev/config/webpack/partial/dev.js
Revert invalid host header PR in archetype app https://github.com/electrode-io/electrode/pull/305/files
Changes will be added to webpackv1 branch.
=> [Patch]revert invalid host header fix

packages/electrode-archetype-react-app-dev/config/webpack/partial/pwa.js
The initial value of entry can be empty which was causing webpack validation errors, causing webpack compilation to fail.
=> archetype-react-app: [bug] [Patch] Update initial entry path for PWA

packages/electrode-archetype-react-component/archetype-gulpfile.js
Archetype component still referred to tasks that were previously deleted, i.e. `dev` and `hot`.
=> archetype-react-component: [Bug] [Patch] Clean remaining dev and hot tasks

packages/generator-electrode/component-add/index.js
The `component-add` generator can accept and initialize props if they are passed to it.
=> generator-electrode: [bug][patch] Accept props as options

samples/universal-react-node/Dockerfile
The dockerfile for the sample app still points to the old server location.
=> Universal-react-node: [bug][path] Update Path for Dockerfile

packages/electrode-archetype-react-app-dev/config/archetype.js, packages/electrode-archetype-react-app-dev/config/webpack/partial/dev.js
A security fix for an insecure configuration for oss app archetype.
Error info: invalid host header.
Fixes: 
Specify Host header to the webpack-dev-server if it exists. Otherwise disable host check.
Demo:
Root cause:
https://github.com/webpack/webpack-dev-server/releases/tag/v2.4.3
https://github.com/webpack/webpack-dev-middleware/releases/tag/v1.10.2
=> archetype-react-app: [minor][bug] Invalid host header fixes

packages/electrode-archetype-react-component/config/webpack/webpack.config.js
This partial no longer exists, so requiring it causes the build to fail.
=> Remove unused stylus partial import

book.json
Plugin: https://plugins.gitbook.com/plugin/add-path-to-parent
Resolve the issue for gitbook iframe url in address bar
=> [gitbook][patch] display iframe url in address bar

packages/generator-electrode/README.md
Fixing `withing` to `within` typo in README.
=> generator-electrode: [docs] [patch] fix typo

packages/electrode-archetype-react-component/config/webpack/partial/styles.js
This fixes an issue where components without config files were failing to build.
cc @jchip a patch release with this would be great
=> Use optional-require to safely read config.js in styles partial

packages/electrode-archetype-react-app-dev/config/webpack/partial/simple-progress.js
New output:
```
webpack compiling: .
building modules: ..........................................................
building modules: ..........................................................
building modules: ..........................................................
building modules: ..........................................................
building modules: ..........................................................
building modules: ..........................................................
building modules: .............................
sealing: .
optimizing: .
basic module optimization: .
module optimization: .
advanced module optimization: .
basic chunk optimization: .
chunk optimization: .
advanced chunk optimization: .
building modules: .
module and chunk tree optimization: . …
```
=> archetype-react-app: [patch] fix webpack simple-progress output

packages/electrode-react-webapp/README.md, packages/electrode-react-webapp/lib/react-webapp.js, packages/electrode-react-webapp/test/data/stats-test-one-bundle.json, packages/electrode-react-webapp/test/spec/index.spec.js
This is a proposed fix for https://github.com/electrode-io/electrode/issues/359
Note: I am unsure whether to categorize this as "feat" or "bug".  It seems like a feature to me, but it is so tiny that it hardly seems to justify that designation!
Details below.
In some cases, it is desirable to have the main JavaScript, CSS and pwa manifests reside on a CDN server while running in production mode.  This is not possible given the current implementation of `electrode-react-webapp`.
This adds a new configuration option, `prodBundleBase`, which defaults to "", but can be configured in the confippet configuration system for plugins.
When specified, this will be prefixed to the url fragment for the main JavaScript bundle(s), css files and pwa manifest files.
This adds several tests to validate …
=> react-web-app: [feat] [minor] Allow an external base URL for resources on production runs (#359)

packages/generator-electrode/generators/app/templates/gulpfile.js, packages/generator-electrode/generators/app/templates/test/server/eslintrc
- set ES6 test flag that is used by the `arch-gulpfile`.
- `test/server` eslint file extends from the new es6 server test file.
=> generator-electrode: [patch] [chore] Set ES6 flag in gulpfile.

packages/electrode-archetype-react-app-dev/config/webpack/partial/index.js, packages/electrode-archetype-react-app-dev/config/webpack/partial/node.js, packages/electrode-archetype-react-app-dev/config/webpack/profile.base.js, samples/universal-react-node/src/client/components/record-form.jsx, samples/universal-react-node/src/client/components/record-store.jsx, samples/universal-react-node/src/client/middleware.js
https://medium.com/@jchipnxd/92b130334b6c
=> archetype-react-app: [major] turn off NodeSourcePlugin for prod build

packages/generator-electrode/component/index.js
This is a fix for redundant prompting `Author Name` and `GitHub username or organization ()`.
Scenario: during electrode:component prompts, hit enter (default value) all the way without specify the author name field name and github username, we should dismiss the redundant `Author Name` and `GitHub username or organization ()` question from electrode:app.
Solution: adding a default value for both.
=> generator-electrode: [patch][bug]generator-default-developer-name

packages/generator-electrode/component-add/index.js, packages/generator-electrode/component/index.js, packages/generator-electrode/generators/app/index.js
Entirely regenerate the `archetype` config folder for the demo-app whenever a new component is added.
=> generator-electrode: [patch] copy entire archetype again for component-add

packages/generator-electrode/package.json
The latest generator electrode@2.2.1 should use electrode-demo-helper@2.0.0 now.
=> generator-electrode: [patch][bug] The latest generator electrode@2.2.1 should be using electrode-demo-helper@2.0.0 now

.travis.yml, packages/electrode-archetype-react-app-dev/config/karma/browser-settings.js
Using karma chrome launcher to start the chrome headless and the updated karma config.
Currently we are using the ChromeHeadless launcher, if we need to pass any custom flags in the future, we can also customize our own launcher by using `customLaunchers`.
reference: https://developers.google.com/web/updates/2017/06/headless-karma-mocha-chai
=> archetype-react-app: [major][feat]Chrome Headless Feature

packages/electrode-archetype-react-component-dev/package.json
@jchip 
We are using `optional-require` and didn't update the requirements. This should fix issues with newer releases of `1.x.x`.
https://github.com/electrode-io/electrode/blob/webpack-1.0/packages/electrode-archetype-react-component/config/webpack/partial/styles.js#L6
=> Add optional-require

packages/electrode-redux-router-engine/lib/redux-router-engine.js, packages/electrode-redux-router-engine/package.json, packages/electrode-redux-router-engine/test/spec/redux-router-engine.spec.js
This is a fix for issue 441.
This solves the issue by replacing "<"'s in the PRELOADED_STATE string with \u003C . The original blog post that alerted me to this problem pointed at a package ( https://github.com/yahoo/serialize-javascript ) that would do the escaping.  It did other things that weren't needed here, and rather than bringing in a 100 line package that did what 5 lines could do, I implemented what was needed here.  In the process, I also noted that they were solving another problem, which is that the \u2028 and \u2029 line and paragraph endings will also mess up the expected results, and so I added that here as well.
If you would prefer to pull in the whole serialize package, I'm happy to do that as an alternative.
```
=============================== Coverage summary …
```
=> [patch][bug] Escape __PRELOADED_STATE__. Fix for #441

packages/electrode-archetype-react-app-dev/config/webpack/partial/extract.js
We were having an issue where the main bundle was including over 100kb (gzipped) of styles in our main entry chunk. This was due to styles that were being required from other chunks, which weren't being extracted.
This change ensures that `ExtractTextPlugin` extracts styles from all chunks, not just the entry chunk. This significantly reduced our main entry chunk size.
cc @jchip it'd be great to get this in and released soon if possible. If there's any reason _not_ to make this change I can adjust this PR to make it optional based on a config property. Thanks!
=> Extract styles from all chunks

packages/electrode-redux-router-engine/lib/redux-router-engine.js, packages/electrode-redux-router-engine/test/routes.jsx, packages/electrode-redux-router-engine/test/spec/redux-router-engine.spec.js, packages/electrode-redux-router-engine/test/test-redux.js
If a component have a dispatch call to update state, the `window.__PRELOADED_STATE__` does not prefetch with the updated state.
Component could call the store dispatch at
- Constructor
```
class Test extends React.Component {
constructor(props) {
super(props);
store.dispatch(); // Call to update state.
}
}
```
- Component will mount
```
class Test extends React.Component {
componentWillMount() {
store.dispatch(); // Call to update state.
}
}
```
- Functional component
```
function Test() {
store.dispatch(); // Call to update state.
return <div>Test</div>
}
```
All above dispatch calls will not be reflected with the new state in the `window.__PRELOADED_STATE__` if we prefetch state before `renderToString()`
According to the code snippet from …
=> Redux state should be preloaded after renderToString.

docs/chapter1/intermediate/build-a-server-plugin.md
- update the `Intermediate: Add Routes` link to point to `/docs/chapter1/intermediate/react-routes/add-routes.md`
=> [PATCH] Fix broken Add Routes link

packages/electrode-archetype-react-app-dev/config/webpack/partial/coverage.js
Fix the inclusion of test/ directory as part of code coverage reporting
Before:
After:
=> [patch][bug]Fix the inclusion of test/ directory as part of code coverage reporting

packages/electrode-react-webapp/README.md, packages/electrode-react-webapp/lib/react-webapp.js, packages/electrode-react-webapp/lib/utils.js, packages/electrode-react-webapp/test/spec/index.spec.js
Modified react-webapp to notice when a nonce value has been provided, and if so attaches
it to any <script> tags and the critical css tag that are generated. See also https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
Fix for #474 
Note: Internal feedback suggested that in some cases a function would be a more general way to get the none value, so added this as an alternative.  Modified docs and tests to test both with a string and the function.
=> [minor][feat] Allow inline scripts to be marked with a nonce for CSP protection

packages/electrode-archetype-react-app-dev/package.json
The latest webpack-dev-server causes incompatibility with webpack v2.7.0. Locking to version 2.5.1 which is the current compatible version.
=> [bug][patch] : Lock to wds@2.5.1

packages/electrode-react-webapp/lib/index.html
**Motivation**
It's slightly unclear why serialized state is placed into `<head>`. The store state might be pretty big sometimes and it looks like it's more critical to parse CSS and page HTML first. 
It would be great to know if there is a strong reason, and possibly make it more obvious why {{PREFETCH_BUNDLES}} is placed before {{SSR_CONTENT}}.
=> Move {{PREFETCH_BUNDLES}} marker after {{SSR_CONTENT}}

packages/generator-electrode/component-add/index.js, packages/generator-electrode/component/index.js, packages/generator-electrode/component/templates/packages/component/src/components/_accordion.jsx, packages/generator-electrode/component/templates/packages/component/src/components/_component.jsx, packages/generator-electrode/component/templates/packages/component/src/styles/_accordion.css, packages/generator-electrode/component/templates/packages/component/src/styles/_component.css, packages/generator-electrode/component/templates/packages/component/src/styles/_raleway.css, packages/generator-electrode/generators/app/templates/src/client/styles/custom.css
Beautify the component generator UI, updated as a expanded accordions. This PR paired with electrode-demo-helper PR: https://github.com/electrode-io/electrode-demo-helper/pull/8
Tested in electrode:component and electrode:component-add generator.
Component Demo:
Component-add Demo:
=> [minor][feat] update component generator UI & using random name for component-add

packages/electrode-react-webapp/lib/react-webapp.js
The caller of the function callUserContent expects a Promise result, so the function should create a promise that is resolved with the output, if the output is not a promise object.
=> [patch][bug] should always return promise object.

packages/electrode-archetype-react-app-dev/config/webpack/webpack.config.test.js
This shows webpack build progress in the command line when running `clap test-frontend`.
It is nice because we want to display that webpack is building before our tests execute but we don't want the coverage displayed all the time.
=> added simple progress

packages/electrode-react-webapp/lib/express/index.js
When trying out the newest version of electrode-react-webapp with an express server, I noticed the promise chain in the electrodeServer configuration in express-server.js was never resolved, since you didn't call the supplied callback function.
=> Fixed registerRoutes never resolving promise from express-server.js

packages/electrode-archetype-react-app-dev/config/babel/babelrc-client, packages/electrode-archetype-react-app-dev/package.json
Same changes for wml archetype app: https://gecgithub01.walmart.com/electrode/electrode-archetype-react-app/pull/243/files
Aim at: Remove unnecessary React propTypes from the production build, as they are only used in development.
=> [major] drop PropTypes for production

packages/electrode-archetype-react-app-dev/config/webpack/partial/test-base.js
This PR fixes the [CORS issue](https://github.com/electrode-io/electrode/issues/102#issuecomment-332284482) when karma is running in `test-watch` and `test-watch-all` modes.
As the result of issue none of the test is running in watch mode. Mocha output:
`Chrome 60.0.3112 (Mac OS X 10.11.4): Executed 0 of 0 ERROR (0.041 secs / 0 secs)`.
=> [patch][bug] Fix CORS issue when running karma tests in `test-watch` and `test-watch-all`

packages/electrode-archetype-react-app-dev/config/babel/babelrc-client, packages/electrode-archetype-react-app-dev/package.json, packages/electrode-archetype-react-app/arch-clap.js, packages/electrode-archetype-react-app/config/babel/.babelrc, packages/generator-electrode/generators/app/templates/src/client/components/demo-code-splitting.jsx, packages/generator-electrode/generators/app/templates/src/client/components/home.jsx, packages/generator-electrode/generators/app/templates/src/client/routes.jsx
Thanks for upgrading to webpack 3. With webpack 3, we could specify chunk name for each dynamically loaded JS file now.
```
import(/* webpackChunkName: "splitting" */ "./components/demo-code-splitting").then(module => {
callback(null, module.default);
});
```
Beside that, it use another set of babel plugins (`babel-plugin-dynamic-import-webpack`, `babel-plugin-dynamic-import-node`) to implement.
=> [minor][feat] implement code splitting support with webpack 3.

packages/electrode-archetype-react-app-dev/config/archetype.js
Enabling css modules for stylus from user config has no effect.
```js
// "/archetype/config/index.js"
module.exports = {
webpack: {
cssModuleStylusSupport: true // has no effect
}
};
```
This PR adds cssModulesStylusSupport to webpack config spec and allows to control this options from user config or env variables.
=> [patch] Add CSS_MODULE_STYLUS_SUPPORT option

packages/generator-electrode/generators/app/templates/_package.json
getting ready to enable React 16, which still has issues, so lock generated app to React 15.
Archetype will be major bump to avoid breaking existing apps that's not locked to React 15.
=> [patch] lock react 15 in generated app

packages/electrode-react-webapp/package.json
electrode-react-webapp doesn't really have dependence on react, so removing it from peerDependencies, and enabling react 16
=> [minor] enable react 16

samples/stylus-sample/package.json, samples/universal-material-ui/package.json, samples/universal-react-node/package.json
stylus-sample, universal-material-ui and universal-react-node are not able to launch without having explicit dependencies of react/react-dom.
=> [minor][bug] unable to launch sample program.

packages/generator-electrode/component/index.js
- npm/yarn install exits immediately on interrupt.
=> [patch][bug] Component Generator refactor install function, exit immediately.

packages/electrode-archetype-react-app-dev/config/webpack/partial/extract-style.js, packages/electrode-archetype-react-app-dev/package.json
- update css optimization plugin to the latest
- update archetype app based on latest css split webpack plugin
=> [bug] set compilerPhase to emit to make sure css split happens after optimization

packages/electrode-archetype-react-component-dev/package.json, packages/generator-electrode/component/templates/demo-app/archetype/config/webpack/component-alias.config.js, packages/generator-electrode/component/templates/packages/component/src/styles/_component.css, packages/generator-electrode/component/templates/packages/component/test/client/components/helpers/_intlEnzymeTestHelper.js
Fixes for new electrode component:
- Fix the issue when updating the package name in `package/[componentName]/package.json`, webpack hot reload will not work.
- update `eslint-config-walmart` to 2.0.0 for `jsx-wrap-multilines` rule (Need a new patch release for https://github.com/walmartlabs/eslint-config-walmart)
- minor fixes for UI (currently the accordion is too wide)
- fixes for component `clap test` eslint errors
=> [patch] Few fixes for new electrode component

packages/electrode-archetype-react-app-dev/config/webpack/partial/extract-style.js
enable defer for deferring css split after optimization.
=> [patch] enable defer based on latest css-split-webpack-plugin

packages/electrode-archetype-react-app-dev/package.json
Seeing an issue on Home app running with archetype app in current master.
```
TypeError: Cannot read property 'type' of undefined
```
To resolve the issue, we need to upgrade to the latest `babel-eslint`.
Related link: https://github.com/eslint/eslint/issues/9767
=> [bug] upgrade babel-eslint

packages/electrode-archetype-react-app-dev/package.json, packages/electrode-archetype-react-component-dev/config/babel/.babelrc, packages/generator-electrode/component/templates/packages/component/_package.json
Require a patch release of electrode archetype app and component.
=> [patch] update component generator

packages/electrode-archetype-react-app/support/babel-run.js
use Path.normalize() to iron out differences between Mac/Windows
=> fix babel-run on a windows environment

packages/electrode-archetype-react-component-dev/config/dependencies/check.json
Resolve below warnings for component archetype
```
Check dependencies failed.
These dependencies are not expected:
- material-ui: version: "^0.20.0"
- electrode-demo-index: version: "^2.0.0"
```
=> [patch] resolve check dependencies warnings

packages/electrode-react-webapp/lib/default-handlers.js, packages/electrode-react-webapp/lib/react-webapp.js, packages/electrode-react-webapp/test/data/chunk-selector.js, packages/electrode-react-webapp/test/spec/hapi.index.spec.js
The app using chunks will need to implement the following to use this.
```js
// /config/utils/chunk-selector.js
module.exports = () => ({
css: [
'app',
'third-party-something',
],
js: 'app',
});
```
```js
// /config/default.js
module.exports = {
// …
webapp: {
// …
options: {
bundleChunkSelector: path.resolve(__dirname, './utils/chunk-selector'),
```
```js
// /archetype/config/webpack/webpack.config.base.js
const appOverrides = {
// …
entry: {
app: [
'babel-polyfill',
// ^ electrode-archetype-react-app-dev/config/webpack/partial/entry.js#L37
path.resolve(appSrc.client, 'app.jsx')
],
'third-party-something': path.resolve(appSrc.client, 'path/to/file'),
},
};
const customMerger = (a, b) => {
return (Array.isArray(a) && Array.isArray(b))
? [].concat(a).concat(b)
: undefined;
}; …
```
=> Support webpack chunks (css)

packages/electrode-archetype-react-component-dev/package.json
before:
> WARN deprecated node-uuid@1.4.8 Use uuid module instead
> WARN deprecated nodemailer@2.7.2 All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
after:
=> [patch] resolve warnings

packages/electrode-archetype-react-app-dev/config/webpack/partial/extract-style.js
Request from newyork project home app.
For IE 10, we need auto-prefixer for transforming `display: flexbox` into `display: -ms-flexbox`
=> [patch] fix autoprefixer for ie10

packages/electrode-archetype-react-component-dev/config/webpack/partial/extract-style.js
Use `optionalRequire` for `archetype/config` folder, based on the `electrode-demo-index` instance. 
`electrode-demo-index` has no demo, its a template other components use for demo. the `archetype/config` is not a required folder and should have a default value for it.
Errors:
=> [patch] optionalRequire archetype/config folder for component archetype

samples/electrode-demo-index/package.json
Inside index.js, we import `component-playground` as a direct usage here: https://github.com/didi0613/electrode/blob/9762bdc8c34fa7ac1e532ae77219d66aa8fdb55c/samples/electrode-demo-index/src/index.js#L4
We need `component-playground` as a dependency here.
Needs this one get merged first:
https://github.com/electrode-io/electrode/pull/733
=> [patch] add demo-component as dependency

packages/electrode-archetype-react-app-dev/config/karma/karma.conf.watch.js
When running `clap test-watch-all`, Chrome has no access to webpack due to a CORS failure.
=> enable cors to debug unit tests

packages/electrode-archetype-react-component-dev/config/webpack/partial/extract-style.js
When component uses css only:
09 04 2018 10:33:58.410:ERROR [config]: Invalid config file!
ReferenceError: `autoprefixer` is not defined
Verified on newly generated ignite component: packages/[component]
=> [patch] autoprefixer + pure css component tests fix

packages/electrode-archetype-react-app/arch-clap.js, packages/electrode-archetype-react-app/support/babel-run.js, packages/generator-electrode/generators/app/templates/src/server/index.js
- allow `dev`, `hot`, and `server-watch` tasks to take arguments to be passed to nodemon.
- add devbrk and hotbrk that automatically set `--inspect-brk` node flag
=> add devbrk and hotbrk tasks

packages/electrode-archetype-react-app-dev/package.json, packages/electrode-archetype-react-app/package.json
Preparing to work with webpack 4.
No need to major bump since isomorphic-loader v2 was to drop support for Node 4 and archetypes v5 already dropped that.
=> update isomorphic-loader to v2

packages/electrode-archetype-react-component-dev/config/webpack/partial/extract-style.js
Add style loader for component archetype to inject css into the <style> tag.
`Bug`:
When we run `npm run test` inside `packages/[component]`, if we import css-modules, for example, to test if the mounted component contains the styles as:
```
const component = mount(<Component />);
expect(component.hasClass(styles.someStyle)).to.equal(true);
```
We got false because `console.log("xxxxxx", styles.baseStyle);` is undefined.
`Fixes`:
After adding style-loader to the archetype component, we got `console.log("xxxxxx", styles.baseStyle);`:
`HeadlessChrome 66.0.3359 (Mac OS X 10.11.6) LOG LOG: 'xxxxxx', 'demo-component__baseStyle___1c6lQ'`
Verified on `css-modules`, `stylus+css-modules`, `sass+css-modules`
=> [patch] component archetype style loader fixes

packages/electrode-redux-router-engine/package.json, packages/electrode-redux-router-engine/test/bad-routes.jsx, packages/electrode-redux-router-engine/test/spec/redux-router-engine.spec.js, packages/generator-electrode/generators/app/templates/_package.json, packages/generator-electrode/generators/app/templates/src/client/app.jsx, packages/generator-electrode/package.json, samples/universal-react-node/package.json, samples/universal-react-node/src/client/app.jsx
Using `render` or `hydrate` when possible
Updated dependencies of `electrode-redux-router-engine` to use React 16 when the application actually runs 
For PWA, since includes `react-notify-toast` (with React 15 direct dependency), react 16 must be listed in package.json to override it
=> using `ReactDOM.hydrate` when content is rendered on the server

packages/electrode-archetype-react-app-dev/config/archetype.js, packages/electrode-archetype-react-app-dev/config/webpack/partial/html-reporter.js, packages/electrode-webpack-reporter/lib/webpack-reporter.js
Since we are currently running multiple electrode apps in our dev environment, we run into a conflict, since the Webpack Reporter always uses the same standard port. This PR introduces a new environment variable called WEBPACK_REPORTER_SOCKET_PORT, that can be used to override the standard port 5000.
=> Default reporter socket port from env

packages/electrode-archetype-react-app-dev/package.json, packages/electrode-archetype-react-app/arch-clap.js
By default, Flow will ignore the 3rd-party libraries which were not written with Flow and leave them untyped. 
The `flow-typed` repo is a collection of high-quality library definitions which allow you to describe the interface of a module or library separate from the implementation of that module/library.
=> [minor] add flow-typed for flow library definitions

packages/generator-electrode/generators/config/templates/default.js
- Otherwise running prod with clap would enable the webpack-dev-hapi plugin because xclap.js could always be setting WEBPACK_DEV_MIDDLEWARE to true
=> webpack-dev-hapi plugin depends on WEBPACK_DEV also

packages/electrode-archetype-react-app-dev/lib/webpack-dev-hapi.js, packages/electrode-archetype-react-app/arch-clap.js, packages/generator-electrode/generators/config/templates/default.js
After webpack compile, should wait for isomorphic to load before showing done message, opening the url, and hot module reload.
=> fix isomorphic loading after webpack compile

packages/generator-electrode/generators/app/templates/src/client/components/demo-pure-states.jsx, packages/generator-electrode/generators/app/templates/src/client/components/demo-states.jsx, packages/generator-electrode/generators/app/templates/src/client/components/home.jsx, packages/generator-electrode/generators/app/templates/src/client/styles/custom.css
Clean up app generator unused css class names & take inline styles out
=> [patch] Clean up app generator unused css class names & take inline styles out

packages/electrode-react-webapp/lib/react-webapp.js
A fix for https://github.com/electrode-io/electrode/issues/848
The following error is gone:
App demo:
=> [patch] webapp WEBPACK_DEV_HOST vs WEBPACK_HOST and cor

packages/electrode-redux-router-engine/lib/redux-router-engine.js, packages/electrode-redux-router-engine/test/routes.jsx, packages/electrode-redux-router-engine/test/spec/redux-router-engine.spec.js
If you use Link from react-router-dom with a basename, for example,
basename: '/my-base' and a `<Link to="/to-target">Test</Link>`
CSR will render it as `<a href="/my-base/to-target">Test</a>`
But SSR will render it as `<a href="/to-target">Test</a>` because the render engine doesn't support basename. 
This PR is to add basename support to the render engine, so we can get same render result CSR vs. SSR.
=> [minor][feat] add basename support for SSR Links

packages/electrode-archetype-react-app-dev/config/archetype.js, packages/electrode-archetype-react-app-dev/config/babel/babelrc-client, packages/electrode-archetype-react-app-dev/config/webpack/partial/extract-style.js, packages/electrode-archetype-react-app-dev/config/webpack/util/detect-css-module.js, packages/electrode-archetype-react-app/arch-clap.js
enable `babel-plugin-react-css-modules` only when needed.
fix the current archetype issue.
sample demo:
getting started
verified shorten css names feature as well
=> fix archetype stylus issue

packages/electrode-archetype-react-app-dev/config/archetype.js, packages/electrode-archetype-react-app-dev/package.json, samples/stylus-sample/src/client/styles/index.styl, xclap.js
This is meant to repro and trigger the stylus issue with the recently released App archetype 5.4.0.
CI should fail (and OK for merge since this is meant to trigger failure).
- but make sure to verify failure is from samples/stylus-sample with `Unnecessary semicolon` error during the build step.
A PR should submit after to verify the issue's fixed.
=> [chore] add stylus-sample to CI

packages/electrode-redux-router-engine/lib/redux-router-engine.js, packages/electrode-redux-router-engine/test/spec/redux-router-engine.spec.js
Instead of a single render entry `engine.render(request)`, allow caller to do these in multiple stages:
```js
const data = engine.startMatch(request);
const errorResult = engine.checkMatch(data);
if (errorResult) {
// can't continue, do something with errorResult
} else {
await this.prepReduxStore(data);
return await this._handleRender(data);
}
```
`data` acquires relevant info through the stages:
- `request`
- `match` - result of react router match
- `location`
- `store` - redux store
=> separate SSR render steps

packages/electrode-react-webapp/README.md, packages/electrode-react-webapp/lib/async-template.js, packages/electrode-react-webapp/lib/react-webapp.js, packages/electrode-react-webapp/lib/render-execute.js, packages/electrode-react-webapp/lib/renderer.js, packages/electrode-react-webapp/test/fixtures/custom-call.js, packages/electrode-react-webapp/test/spec/hapi.index.spec.js, packages/electrode-react-webapp/test/spec/token.spec.js
- allow setting a flag `insertTokenIds` in route options so the renderer will insert token IDs as HTML comment in the final output
Helps with debugging.
=> support insert token ids to output for debugging

packages/generator-electrode/generators/app/templates/src/client/actions/index.jsx, packages/generator-electrode/generators/app/templates/src/client/components/demo1.jsx, packages/generator-electrode/generators/app/templates/src/client/components/demo2.jsx, packages/generator-electrode/generators/app/templates/src/client/components/home.jsx, packages/generator-electrode/generators/app/templates/src/client/components/nav.jsx, packages/generator-electrode/generators/app/templates/src/client/reducers/index.jsx, packages/generator-electrode/generators/app/templates/src/client/routes.jsx, packages/generator-electrode/generators/app/templates/src/client/styles/demo1.css, packages/generator-electrode/generators/app/templates/src/client/styles/demo2.css, packages/generator-electrode/generators/app/templates/src/client/styles/nav.css, packages/generator-electrode/generators/app/templates/src/server/routes/init-top.jsx, packages/generator-electrode/generators/app/templates/test/client/components/home.spec.jsx
=> [minor] update the generator with a new navigation & demos

packages/electrode-archetype-opt-sass/README.md, packages/electrode-archetype-opt-sass/optional-check.js, packages/electrode-archetype-opt-sass/package.json, packages/electrode-archetype-react-app-dev/config/webpack/partial/extract-style.js, packages/electrode-archetype-react-app-dev/package.json, packages/electrode-archetype-react-app/config/archetype.js, packages/electrode-archetype-react-component-dev/config/webpack/partial/extract-style.js, packages/electrode-archetype-react-component-dev/package.json, packages/electrode-archetype-react-component/config/archetype.js
* When specifying nodeSass:true
> optional dep check passed electrode-archetype-opt-node-sass@1.0.0-fynlocal_h- preinstall script exit with code 0
```
fyn stat node-sass
> node-sass matched these installed versions node-sass@4.9.3
> node-sass@4.9.3 has these dependents sass-loader@6.0.7
fyn stat sass-loader
> sass-loader matched these installed versions sass-loader@6.0.7
> sass-loader@6.0.7 has these dependents
```
* Without specifying nodeSass or nodeSass: false
> executed electrode-archetype-opt-node-sass@1.0.0-fynlocal_h- preinstall failed shell cmd 'node optional-check.js' exit code 1
```
fyn stat node-sass
> node-sass is not installed
fyn stat sass-loader
> sass-loader is not installed
```
Tested on `universal-react-node` sample.
electrode issue link: …
=> make node-sass optional

packages/electrode-archetype-react-app-dev/config/archetype.js, packages/electrode-archetype-react-app-dev/config/webpack/partial/extract-style.js
We use optimize-css-assets-webpack-plugin to optimize CSS, which internally uses cssnano, which default to mutate z-index. 
since that's generally a bad idea, we are defaulting this behavior to off.
Further, since optimize-css-assets-webpack-plugin takes an options object, user can now specify the following in `archetype/config/index.js`:
```js
module.exports = {
webpack: {
optimizeCssOptions: {
cssProcessorOptions: {
zindex: true
}
}
}
};
```
This will turn z-index mutation back on, and any allow any other optimize-css-assets-webpack-plugin options to be specified, see its docs on options it supports.
=> update optimize css to not touch zindex by default

packages/electrode-archetype-react-app/arch-clap.js
Currently `build-analyze` command analyzes the entry with hardcoded name `main` only.
If you happen to change your entry name in the `entry.config.js` this command will fail.
This PR fixes this by just picking up the first entry from the `stats.json`.
=> Improve `build-analyze` command

packages/electrode-react-webapp/lib/react/content.js
As they end up with the tag `<scriptundefined>` at the moment which seems unintended
=> [patch][bug] handle text based scripts

packages/electrode-react-webapp/lib/hapi/index.js, packages/electrode-react-webapp/lib/react-webapp.js, packages/electrode-react-webapp/test/spec/hapi.index.spec.js
electrode-react-webapp: Allow user to set `responseForBadStatus` option to null, so even if content return bad status, still return the rendered result verbatim.
=> allow disabling responseForBadStatus

docs/chapter1/intermediate/app-archetype/webpack-config.md, packages/electrode-archetype-react-app-dev/config/webpack/util/generate-config.js, packages/webpack-config-composer/lib/concat-method.js, packages/webpack-config-composer/lib/index.js, packages/webpack-config-composer/lib/partial.js, packages/webpack-config-composer/lib/profile.js, packages/webpack-config-composer/test/spec/index.spec.js, packages/webpack-config-composer/test/spec/profile.spec.js
- add three new APIs to webpack-config-composer `addPartial`, `addProfile`, and `addPartialToProfile`
- update archetype generate-config:
- add a `user` profile to allow custom code to easily add config partials
- use webpack config composer to compose user's config object
- update webpack config customization doc to show the easier way
=> Update webpack config composer to make it easier to customize

packages/electrode-archetype-react-app-dev/lib/webpack-dev-hapi.js
Resolve warnings:
```
TypeError: Webpack is not a constructor
at Object.register (/Users/s0d00px/Electrode/electrode/samples/universal-react-node/node_modules/electrode-archetype-react-app-dev/lib/webpack-dev-hapi.js:60:20)
at Object.target [as register] (/Users/s0d00px/Electrode/electrode/samples/universal-react-node/node_modules/__fv_/11.4.0/joi/lib/types/object/index.js:76:34)
at each (/Users/s0d00px/Electrode/electrode/samples/universal-react-node/node_modules/hapi/lib/plugin.js:310:14)
```
=> [major] webpack4: update ProgressPlugin to webpack4

packages/electrode-node-resolver/lib/webpack-plugin.js
resolves:
```
(node:40534) DeprecationWarning: Resolver: The callback argument was splittedinto resolveContext and callback.
(node:40534) DeprecationWarning: Resolver#doResolve: The type arguments (string) is now a hook argument (Hook). Pass a reference to the hook instead.
```
=> [major] wepack4: update node-server-webpack-plugin

packages/electrode-archetype-react-app-dev/config/webpack/partial/uglify.js
Use multi-process parallel running to improve the build speed.
Time: 34879ms -> Time: 28470ms
=> [major] Webpack4: decrease compilation time

packages/electrode-archetype-react-app-dev/config/archetype.js, packages/electrode-archetype-react-app-dev/config/webpack/partial/dll-load.js, packages/electrode-archetype-react-app-dev/config/webpack/partial/index.js, packages/electrode-archetype-react-app-dev/config/webpack/profile.base.js, packages/electrode-archetype-webpack-dll-dev/config/webpack/util/context.js, packages/electrode-archetype-webpack-dll-dev/lib/save-module-versions.js, packages/electrode-archetype-webpack-dll/arch-clap-tasks.js
- Add webpack config to support loading DLL module generated with electrode DLL archetype
- Save versions of modules packed into the DLL
=> Electrode DLL loading support

packages/electrode-archetype-react-app-dev/config/webpack/partial/babel.js, packages/electrode-archetype-react-app-dev/config/webpack/partial/dll-load.js, packages/electrode-archetype-react-app-dev/config/webpack/partial/resolve-loader.js, packages/electrode-archetype-react-app-dev/config/webpack/partial/resolve.js
Lodash (as of v4.17.4) adds 72 KB of minified code to the bundle. But if you use only, like, 20 of its methods, then approximately 65 KB of minified code does just nothing.
=> [major] webpack 4: Decrease bundle size, load lodash methods needed only

packages/electrode-archetype-react-app-dev/lib/webpack-dev-hapi.js
Some use case may required force skipping webpack dev middleware in dev mode.
=> support skipping webpack dev middleware in dev mode

packages/electrode-archetype-react-component-dev/package.json
electrode-node-resolver v2 is for webpack 4. Rollback to v1 instead.
=> [patch] Roll back electrode-node-resolver version for component for webpack 3

packages/electrode-archetype-react-app/arch-clap.js, packages/electrode-archetype-react-app/config/archetype.js, packages/electrode-archetype-react-app/lib/warn-yarn.js
- log warning about using yarn
- make error clearer when the module electrode-archetype-react-app-dev is not installed
=> better errors and warnings

packages/electrode-archetype-react-component-dev/package.json
```
npm WARN deprecated postcss-cssnext@2.11.0: 'postcss-cssnext' has been deprecated in favor of 'postcss-preset-env'. Read more at https://moox.io/blog/deprecating-cssnext/
```
Remove deprecated & extra postcss-cssnext
=> [patch] component archetype webpack 4: remove extra postcss-cssnext

packages/electrode-webpack-reporter/package.json
https://github.com/zilverline/react-tap-event-plugin/issues/121
breaks webpack-reporter webapp
lock react versions to fix
=> lock react versions to avoid issue

packages/electrode-react-webapp/lib/render-execute.js
Prevents the following warning
(node:25733) Warning: a promise was created in a handler at /Users/vn034pt/walmart/tagger/node_modules/electrode-react-webapp/lib/render-execute.js:42:24 but was not returned from it, see http://goo.gl/rRqMUw
=> Return on every promise

packages/electrode-archetype-react-app-dev/config/webpack/partial/dev.js
concatenateModules flag is to find segments of the module graph which can be safely concatenated into a single module.
This is not enabled under dev mode with our previous webpack 3 config. It is newly added for improving performance with webpack v4.  However, it causes some issues when testing with home app from `@walmart/feds-wmt-header` module. 
Change back to default: `concatenateModules: false` in dev and `concatenateModules: true` in prod.
=> [patch] webpack 4: concatenateModules false

packages/electrode-archetype-react-app-dev/lib/webpack-middleware.js
This fixes https://github.com/electrode-io/electrode/issues/1087
The webpack reporter was rendering when no errors were present. This should not be the expected behaviour since the build still passes
=> [patch][bug] webpack reporter should not render when no errors

packages/electrode-react-webapp/lib/react-webapp.js, packages/electrode-react-webapp/test/spec/react-webapp.spec.js
`WEBPACK_DEV` is already being checked in this way, we should do the same for this environment variable. Ran into this bug trying to disable it via a command line export.
=> [patch] check for "false" on WEBPACK_DEV_HTTPS

packages/electrode-archetype-react-component/archetype-clap.js
The .babelrc was being regenerated every time because the `rc` variable was only set within the `if` block's scope
=> [patch][bug] fix babelrc being overriden

packages/electrode-archetype-react-app-dev/package.json, packages/electrode-archetype-react-app/package.json
fix https://github.com/electrode-io/electrode/issues/1107
=> [patch][bug] put @babel/runtime in electrode-archetype-react-app

packages/electrode-archetype-react-app/arch-clap.js
* TypeScript extensions added to nodemon command
* Removed the webpack-dev-middleware condition that made nodemon not watch the server folder. The server folder isn't built with webpack, so it wasn't being watched by anything.
=> [minor][bug] fix server watch when using typescript

packages/electrode-archetype-react-app-dev/lib/fake-res.js
webpack-dev-middleware is calling this function as of 3.6.1 so Electrode breaks when trying to load webpack assets
=> [patch] add getHeader() to middleware

packages/electrode-archetype-react-app-dev/config/archetype.js
define extendBabelLoader in default config to enable the babel config to be overridden from app
extendBabelLoader is used here
https://github.com/electrode-io/electrode/blob/v5.x.x/packages/electrode-archetype-react-app-dev/config/webpack/partial/babel.js#L43
=> [PATCH]define extendBabelLoader in default config

packages/electrode-react-webapp/lib/utils.js, packages/electrode-react-webapp/test/spec/utils.spec.js
As for user defined entry point other than `main`, the bundle name after bundle selection should include the chunk name defined by user. 
For example `default.foo.bundle.js` as default bundle, and the corresponding es6 bundle shall be `es6.foo.bundle.js`
=> fix entry chunk name in multi-bundle selection

packages/electrode-archetype-react-app/arch-clap.js
According to issue https://github.com/electrode-io/electrode/issues/1151, the `*.spec.js` and `*.test.js` within `src/client` and `src/server` shall be removed in `lib` after build. 
But currently, task `.build-lib:delete-babel-ignored-files` only work for `src/client`. 
Correct `libDir` will fix this issue
=> fix test and spec file in `src/server` cannot be removed after build

packages/electrode-archetype-react-app-dev/config/babel/babelrc-client.js
If multiple targets exists, add `useBuiltIns: "entry"` and `corejs` version in presets to customize core-js size in bundle according to target
=> Add useBuiltIns for @babel/preset-env

packages/electrode-react-webapp/lib/async-template.js, packages/electrode-react-webapp/lib/react/content.js, packages/electrode-react-webapp/lib/react/token-handlers.js, packages/electrode-react-webapp/lib/render-context.js, packages/electrode-react-webapp/lib/render-output.js, packages/electrode-react-webapp/lib/utils.js, packages/electrode-react-webapp/package.json, packages/electrode-react-webapp/test/spec/hapi17.index.spec.js, packages/electrode-react-webapp/test/spec/render-output.spec.js
If app returns SSR content result as a stream or set the flag `useStream` then generate the output for the index.html as a readable stream using https://www.npmjs.com/package/munchy
Prep work for enabling React 16 `renderToNodeStream` API for SSR
=> [minor] allow content to specify use streams for generating output

packages/electrode-archetype-react-component-dev/config/webpack/partial/uglify.js, packages/electrode-archetype-react-component-dev/package.json
this replaces uglify with terser as uglify plugin does not handle es6 code correctly.
it looks like uglify-es is no longer maintained and terser is replacement being used for Webpack 4, this version is for legacy which supports Webpack 3 
also we only want uglification of code on prod builds, a check has been added for this.
=> replace uglify with terser

packages/electrode-archetype-react-app-dev/config/webpack/partial/babel.js, packages/electrode-archetype-react-app/arch-clap.js
define `envTargets` in `archetype/config/index.js`
use `clap dev --target=es6` or alias `clap dev-es6`
=> set babel env target for dev mode with archetype v5

packages/opt-archetype-check/optional-check.js
optional archetype packages check app's package.json `dependencies` and `optionalDependencies` and if they contain the optional package, then proceed to install it.
This would allow app to opt into an optional archetype by specifying it in dependencies.
TBD: archetype needs to set `archetype.options[tag]` if app chose to opt-in through dependencies.
=> opt archetype install if app has it in dependencies

packages/generator-electrode/generators/app/index.js
since all optional packages are default to be installed. change the generators to create `archetype/config/index.js` only if some optionals are disabled explicitly
=> modify generator

packages/electrode-archetype-opt-critical-css/optional-check.js, packages/electrode-archetype-opt-eslint/optional-check.js, packages/electrode-archetype-opt-inferno/optional-check.js, packages/electrode-archetype-opt-jest/optional-check.js, packages/electrode-archetype-opt-karma/optional-check.js, packages/electrode-archetype-opt-mocha/optional-check.js, packages/electrode-archetype-opt-postcss/optional-check.js, packages/electrode-archetype-opt-react/optional-check.js, packages/electrode-archetype-opt-react/package.json, packages/electrode-archetype-opt-sass/optional-check.js, packages/electrode-archetype-opt-sinon/optional-check.js, packages/electrode-archetype-opt-typescript/optional-check.js, packages/opt-archetype-check/optional-check.js, packages/opt-archetype-check/package.json, packages/opt-archetype-check/test/test1.js
This allow archetype to include an opt archetype by default, but user can specify another one in their `devDependencies` with a diff major version to override.
=> optional check skip if user dep on a diff major version

packages/opt-archetype-check/optional-check.js
Fix issue where if user doesn't have `archetype/config`, the code throws and by pass a bunch of other checks.
=> check user's dep even if no archetype config found

packages/electrode-archetype-react-app-dev/config/archetype.js, packages/electrode-archetype-react-app-dev/config/babel/babelrc-client.js, packages/electrode-archetype-react-app-dev/package.json
maybe need to add support for decorators, which will be helpful for `mobx` users, since mobx uses decorators much. 
and the plugin `@babel/plugin-proposal-decorators` needs to be put before `@babel/plugin-proposal-class-properties`, which is not easy to override in users' `src/client/.babelrc.js`, since the merged `plugins` cannot change the order of original plugins.
=> [feat] add support for proposal decorators

packages/electrode-archetype-react-app-dev/config/webpack/partial/entry.js, packages/subapp-redux/lib/index.js, packages/subapp-redux/src/index.jsx, packages/subapp-util/lib/index.js, samples/poc-subapp/fyn-lock.yaml, samples/poc-subapp/src/02.main-body/main-body.jsx, samples/poc-subapp/xclap.js
Redux store reducers hot module reload requires user's `createStore` method to detect code change and accept hot module update, but also need to call `store.replaceReducers`.
This is a fairly tricky thing to do automatically, so the approach is to assume user's reducers is named as `reducers[.js|.jsx]`, and generate a JS to import it and provide a `createStore` method for the subapp to hot accept module and replace reducers.
But if user's subapp provide its own `reduxCreateStore` method, then nothing is done.  User needs to handle HMR and `store.replaceReducers`
=> scan subapp dir for reducers and create HMR createStore method

packages/electrode-archetype-react-app-dev/config/webpack/partial/subapp-chunks.js, packages/subapp-web/lib/util.js
```
maxAsyncRequests: 500,
maxInitialRequests: 500,
```
aggressively generate common bundles for code that subapps share.
=> update config to split more vendor/shared bundles

packages/electrode-archetype-react-app-dev/lib/dev-admin/admin-server.js, packages/electrode-archetype-react-app-dev/lib/dev-admin/console-io.js, packages/electrode-archetype-react-app-dev/lib/dev-admin/middleware.js, packages/electrode-archetype-react-app-dev/lib/dev-admin/webpack-dev-relay.js, packages/electrode-archetype-react-app-dev/package.json, packages/electrode-archetype-react-app-dev/test/spec/dev-admin/webpack-dev-relay.spec.js, packages/electrode-archetype-react-app/package.json, samples/hapi-app/fyn-lock.yaml, samples/hapi-app/package.json, samples/universal-react-node/fyn-lock.yaml
With dev-admin server, it's possible to setup IPC between webpack dev server and app server through `process.send`.  Use that to transfer isomorphic config from WDS to app, instead of a file on disk and relying on file watcher, causing all kinds of timing issues.
=> use process.send to transfer isomorphic config from wds to app

packages/electrode-archetype-react-app-dev/config/webpack/util/generate-config.js
`webpack.config.js`, `webpack.config.dev.js` failed to load from the `./archetype/config` directory.  it looks for 'production.js', 'development.js' instead, which is not backward compatible with existing apps.
=> Fix config fail to load

packages/electrode-archetype-react-app/lib/features.js
Also, search for devOnly in locally installed package if not available in npm registry data.
=> If devOnly is undefined, default to true.

packages/electrode-archetype-opt-critical-css/optional-check.js, packages/electrode-archetype-opt-eslint/optional-check.js, packages/electrode-archetype-opt-flow/optional-check.js, packages/electrode-archetype-opt-inferno/optional-check.js, packages/electrode-archetype-opt-jest/optional-check.js, packages/electrode-archetype-opt-karma/optional-check.js, packages/electrode-archetype-opt-less/optional-check.js, packages/electrode-archetype-opt-mocha/optional-check.js, packages/electrode-archetype-opt-phantomjs/optional-check.js, packages/electrode-archetype-opt-postcss/optional-check.js, packages/electrode-archetype-opt-pwa/optional-check.js, packages/electrode-archetype-opt-react-intl/optional-check.js, packages/electrode-archetype-opt-react/optional-check.js, packages/electrode-archetype-opt-sass/optional-check.js, packages/electrode-archetype-opt-sinon/optional-check.js, packages/electrode-archetype-opt-stylus/optional-check.js, packages/electrode-archetype-opt-typescript/optional-check.js, packages/opt-archetype-check/optional-check.js
- If both archetype config and package.json contain a reference to the feature package, default to enabled (even if the archetype config specifies disabled).
- Display message as a warning instead of an error.
- Display additional information indicating that using archetype/config to enable features is going to be deprecated
=> Do not fail the optional-check for dual-selection

packages/electrode-archetype-react-app/lib/features.js
This change allows users to stay in the features menu and select each feature to turn it on/off freely using arrow keys and the spacebar. Users can use the "enter" key at any point to signal they are done selecting features. At this point, the `package.json` is altered to reflect the users' feature selections.
This makes use of `prompts` "multiselect" datatype.
=> Create a features menu for random-access feature selection

packages/electrode-archetype-react-app-dev/lib/dev-admin/admin-server.js, packages/electrode-archetype-react-app-dev/lib/dev-admin/dev-hapi.js, packages/electrode-archetype-react-app-dev/lib/dev-admin/log-parser.js, packages/electrode-archetype-react-app-dev/lib/dev-admin/log-reader.js, packages/electrode-archetype-react-app-dev/lib/dev-admin/log.html, packages/electrode-archetype-react-app-dev/lib/dev-admin/middleware.js, packages/electrode-archetype-react-app-dev/test/spec/dev-admin/log-parser.spec.js, packages/electrode-archetype-react-app/lib/winston-logger.js
- Change Winston logger to json mode for easy parsing
- Intercept stdout and stderr in the application server
- Recognize the following log formats:
- winston
- electrode-fyi
- node-bunyan
- Attach badge for recognized log formats
- Use Winston to log parsed message at appropriate log level
- Create a web interface for viewing logs
- Filter by specific log levels (e.g. debug, info, error)
- Refresh the logs to see the newest lines
- Preserve console ansi coloring
- Create a console interface in the dev-admin server to display logs
- Menu item to display all logs ("l")
- Menu items to display only logs with at least a certain level ("0" - "6")
=> dev-admin server: create a web interface for viewing console log events

packages/subapp-redux/src/index.jsx, packages/subapp-redux/src/shared.js, packages/subapp-redux/test/spec/index.spec.js
This introduces a new option for `reduxLoadSubApp` named `reduxShareStore`. This can be either `true` (to use the default store) or a string (to use a named store). When using a shared store, the `reduxReducers` option must be an object of named reducers so the system can properly merge them, or the store must use the `reduxCreateStore` option (which will ignore the `reduxReducers` attribute).
=> Subapp redux store sharing

packages/subapp-web/.babelrc.js, packages/subapp-web/.gitignore, packages/subapp-web/lib/index.js, packages/subapp-web/package.json, packages/subapp-web/xclap.js
transpile the code in `src` to three targets:
1. `browser` - uniminify code meant for browser (for development)
2. `dist` - minified code for browser
3. `node-dist` - code for node.js
=> transpile src to multi targets

docs/guides/subapps.md
There are no inbound links to this page yet.
=> First pass of an Electrode subapp guide

packages/subapp-web/lib/load.js
It's more efficient to embed large JSON data as text and `JSON.parse` it, instead of embed as JS Object directly. 
https://quipblog.com/efficiently-loading-inlined-json-data-911960b0ac0a
=> embed large initial state as JSON text

packages/electrode-react-webapp/lib/hapi/plugin16.js, packages/electrode-react-webapp/lib/hapi/plugin17.js
Summary:
Currently electrode returns 302 for any redirect response.
Added hapijs redirectcode to the response stream
=> Fixing electrode redirect issue (only returns 302). 

packages/subapp-web/lib/util.js, packages/subapp-web/test/spec/util.spec.js
#problem 
the `loadAssetsFromStats` function will return an empty object when `stats.json` cannot be found. This results in undefined behavior downstream: see the code path in #1558 as an example.
Should this fail -- whether from unexpected behavior or invalid inputs, the error delivered to the end-user is unrelated to the original failure.
#solution 
Instead of preempting a file io error by returning an empty object, the function should throw with a helpful message. If consumers expect the file to be missing, the callsite should handle as necessary. Otherwise, the end-user get's an idea of what failed.
closes #1558
=> fix(throw on missing stats.json)

packages/xarc-app-dev/lib/dev-admin/admin-server.js, packages/xarc-app-dev/lib/dev-admin/redbird-proxy.js
It's not immediately obvious from the dev-admin panel what processes are associated with what port. This can lead to some confusion, as outlined [here](https://github.com/electrode-io/electrode/issues/1559)
Make the dev admin panel more transparent without being verbose, with things a dev will want/need to see at some point:
* Output pid alongside the process that's started / stopped, e.g.:
* "your app server (PID: 59264) started"
* "your app server (PID: 59264) exited code 0"
* Output tree to communicate proxy associations: 
* <img width="513" alt="Screen Shot 2020-03-16 at 4 49 25 PM" src="https://user-images.githubusercontent.com/2519820/76808964-7d248980-67a6-11ea-894d-c84eb1d0fce9.png">
Additional Small change: 
* Removed signal reporting when falsy:
* ""your app server exited code 0 …
=> fix: add helpful output to admin console and dev proxy

packages/subapp-web/lib/util.js, packages/xarc-webpack/lib/partials/dev.js, packages/xarc-webpack/lib/partials/output.js, packages/xarc-webpack/lib/partials/subapp-chunks.js
content hash in dev mode is bad, because it breaks HMR.
So just remove content hash from chunk names all together.
=> fix: remove content hash from chunk names

docs/guides/subapps.md, packages/create-app/template/src/demo2/subapp-demo2.js
default args specify `initialData`, but `{ context, request }` are actually passed
update to use `{ context, request }`
=> fix: correct prepare args

packages/subapp-server/lib/setup-hapi-routes.js, packages/subapp-server/test/spec/setup-hapi-routes.spec.js
Previously it simply ended up with 
```
Error: Cannot wrap an error
at new module.exports (...@hapi/hoek/lib/error.js:23:19)
at Object.module.exports [as assert] (...@hapi/hoek/lib/assert.js:20:11)
at internals.Toolkit.response (...@hapi/hapi/lib/toolkit.js:174:14)
at handler (...subapp-server/lib/setup-hapi-routes.js:189:14)
```
Now it would provide you with the underlying issue, such as
```
TypeError: Class constructor IndexPage cannot be invoked without 'new' at JsxRenderer._render (...electrode-react-webapp/lib/jsx/JsxRenderer.js:188:25) at handleElementResult (...electrode-react-webapp/lib/jsx/JsxRenderer.js:156:30) at JsxRenderer._render (/...electrode-react-webapp/lib/jsx/JsxRenderer.js:179:14) at Promise.each.then  etc etc
```
=> [patch] provide original error for debug purposes

packages/xarc-app-dev/lib/dev-admin/log.html
- Use Menlo font
- Use DOM to append entries
- Use URL hash to remember settings
=> improve HTML viewer

packages/subapp-web/lib/load.js
hey @jchip and @christianlent! I can't actually seem to get fyn bootstrap to run successfully, so i'm struggling to run tests, etc. 
So i figured I'd at least send this PR to clarify what I'm suggesting we do. 
Basically, this would allow us to run `instance.getInitialState()` and thereby defer the reading of that data instead of blocking on that with the inline script (as we discussed).
=> added: mechanism to defer initial state read for sub apps

packages/xarc-app-dev/lib/dev-admin/admin-server.js, packages/xarc-app-dev/lib/dev-admin/cleanup.js, packages/xarc-app-dev/lib/dev-admin/index.js, packages/xarc-app-dev/package.json, packages/xarc-app/lib/winston-logger.js
fixes https://github.com/electrode-io/electrode/issues/1631
CI failing because node 14 added recently.  There are some problem with node 14 and need to remove it later.
=> feat: dev-admin cleans child process automatically

packages/xarc-app-dev/lib/dev-admin/admin-server.js, packages/xarc-app-dev/lib/dev-admin/automation-io.js, packages/xarc-app-dev/lib/dev-admin/index.js, packages/xarc-app-dev/package.json
If `clap dev` is being used in CI env, then dev admin will not have interactivity capabilities enabled.
=> fix: disable dev admin interactivity in CI

packages/xarc-create-app/package.json, packages/xarc-create-app/src/check-dir.js, packages/xarc-create-app/src/create.js, packages/xarc-create-app/src/prep-app-dir.js, packages/xarc-create-app/template/_package.js
simplify quick start instruction to be:
`npm init @xarc/app my-app`
further instruction will be shown by the create code.
```
Created react/node webapp in directory 'my-app'. To start development, please run:
cd my-app
npm install
npm run dev
For more info, please check the README.md file.
```
=> create-app: take app directory as argument

packages/subapp-server/lib/setup-hapi-routes.js, packages/subapp-util/lib/index.js, packages/xarc-webpack/lib/partials/entry.js, packages/xarc-webpack/package.json, samples/demo-tree-shaking/package.json, samples/react-jest-app/package.json
Directory structure of individual subapps:
```
my-sub-app
├── README.md
├── package.json
├── src
........├── index.js
........├── subapp.js
........├── server.js
........├── reducers.js
```
Each subapp should be exporting the manifest and sub-app options as below
```
const subAppOptions = {
serverSideRendering: false
};
const manifest = {
type: "app",
name: "Demo1",
entry: require.resolve("./subapp"),
serverEntry: require.resolve("./server"),
reducers: require.resolve("./reducers")
};
module.exports = { subAppOptions, manifest `};
```
The users must provide absolute paths for `entry`, `serverEntry` and `reducers`
**Publishing** : The code must be transpiled to node executable format before publishing the package.
**Main app:**
Create a file named `subapps-modules.js` in `src` and export …
=> Loading subapps from a different repo

packages/xarc-webpack/README.md, packages/xarc-webpack/package.json, packages/xarc-webpack/src/index.ts, packages/xarc-webpack/src/partials/dll-entry.ts, packages/xarc-webpack/src/partials/extract-style.ts, packages/xarc-webpack/src/partials/index.ts, packages/xarc-webpack/src/util/generate-config.ts
Making use of typedoc and typescript, adding some explicit APIs for customizing webpack configs:
- all webpack config partials are explicitly export so they are easily selectable
- API `applyPartials` to easily choose and pick partials to construct final webpack config
- export `profiles` that are easily selectable to see what partials they included.
- export `defaultConfigs` to just use them in user's `webpack.config.js`
=> adding new API for customizing webpack configs

packages/subapp-web/lib/init.js, packages/subapp-web/src/subapp-web.js
https://jira.walmart.com/browse/CEECORE-1751
=> Load cdn mapping script for non js/css assets only if cdn option isenabled

packages/subapp-util/lib/index.js, packages/subapp-util/test/data/subapp4/src/index.js, packages/subapp-util/test/data/subapp4/src/server.js, packages/subapp-util/test/data/subapp4/src/subapp-conf.js, packages/subapp-util/test/data/subapp4/src/subapp-manifest.js, packages/subapp-util/test/spec/index.spec.js, packages/subapp-web/lib/init.js, packages/subapp-web/lib/load.js, packages/subapp-web/test/spec/init.spec.js
https://jira.walmart.com/browse/CEECORE-1748
=> Refactoring to improve performance

packages/xarc-app-dev/src/lib/load-xrun-tasks.ts
since only `@xarc/webpack` depends on `webpack`, to get the exact CLI, first check `node_modules/.bin` inside `@xarc/webpack` first.
=> fix: ensure to have exact webpack CLI command

packages/subapp-server/lib/fastify-plugin.js
Usage:
For selected routes:
```
"/": {
pageTitle: "Welcome to Electrode",
subApps: ["./home", "./demo1", "./demo2"],
auth: ["electrode-sso"], // auth strategies decorated in fastify instance
}
},
```
To add SSO for all the routes, set `auth` as plugin option.
```
plugins: {
"subapp-server": {
enable: true,
options: {
auth: ["electrode-sso"]
}
},
}
```
Send To Client By Cookies:
```
"/": {
pageTitle: "Welcome to Electrode",
subApps: ["./home", "./demo1", "./demo2"],
auth: ["electrode-sso"], // auth strategies decorated in fastify instance
settings: {
preHandler: (request, reply, done) => {
if (request.auth && request.auth.credentials) {
electrodeCookies.set("SSO_CRED", request.auth.credentials, { request, secure: true });
}
done();
},
}
},
```
=> feature: add support for electrode-sso

packages/subapp-web/lib/init.js
Fixing the missing return statement. This was resulting in all the `initialize` method getting ignored.
cc @divyakarippath @jchip
=> Fix the missing return. This was causing the issue in not invoking the route initialize method

packages/subapp-server/lib/fastify-plugin.js, packages/subapp-server/lib/register-routes.js, packages/subapp-server/lib/setup-hapi-routes.js
Fixes https://jira.walmart.com/browse/CEECORE-2000
Basepath was not getting updated in `@walmart/electrode-ui-config` which was causing the issue. Setting `uiConfig` in `routeOptions` will fix this.
In `@gtp/x-index`, dynamic data token handler will read the `uiConfig` from `routeOptions` and set it to `window._wml.config`. `@walmart/electrode-ui-config` reads the ui config and basepath from there and update the fullApiPath accordingly.
=> Set ui config to route options

packages/xarc-app/src/index.ts
Issue: Currently css modules with SSR works only during dev mode. It is because the generated class name during ssr  (css-require-hook) vs webpack build uses different generated scope names.
Also, there is strict check for `options.cssModuleHook` as boolean but code expects an object to get the generated Scope name from user land. Users won't be able to override the generatedScopeName value.
Fix: Allow objects to be passed from users to control options passed to css module require hook and default to short names for production mode.
cc @jchip @divyakarippath
=> Fix CSS Modules generated scope name based on prod vs dev mode.

packages/xarc-jsx-renderer/src/JsxRenderer.ts
`RenderOutput::close()` returns a Promise in some use-cases. Hence need to `await` if calling it.
Otherwise the app might throw `Cannot wrap a promise` error.
`RenderOutput::close()` returns a promise in it's else part here: https://github.com/electrode-io/electrode/blob/28dea6de7ef88f07318274b25c1d9a42a046864e/packages/xarc-render-context/src/RenderOutput.ts#L73
=> await on RenderOutput::close()

packages/xarc-app/package.json, packages/xarc-webpack/src/partials/extract-style.ts
https://jira.walmart.com/browse/CEECORE-1960
To support below usage for css modules with SSR
```
import styles from "./demo1.module.css";
<div className={styles.demo1}>
```
Related PR - https://github.com/electrode-io/isomorphic-loader/pull/25
=> Server side support for css modules

packages/xarc-webpack/src/util/dll-util.ts
Currently it assumes that packages are directly under `node_modules` of current directory.
Instead, use node module resolution to figure out the correct path for package dir.
Also, use `<package-name>/package.json` to handle the `main` and `browser` fields.
cc @jchip @divyakarippath
=> Fix dll loading issue inside  monorepo

packages/subapp-web/lib/init.js, packages/subapp-web/lib/load.js, packages/subapp-web/src/index.js, packages/subapp-web/src/subapp-web.js, packages/subapp-web/test/spec/index.spec.js, packages/subapp-web/test/spec/init.spec.js
- pass namespace for the generated markBundlesLoaded script
- allow namespace as option for bundleAsset script id so that app can be run in standalone mode as well as integration mode.
- use the correct state while calling xarc.setBundle - State can be either 0 or 1 instead of boolean
- use setBundle instead of directly touching runtimeInfo.bundles
- add/update tests for the same.
cc @jchip
=> Fix subapp namespacing issues

packages/xarc-react-query/src/browser/index.tsx, packages/xarc-react-query/src/node/index.tsx, packages/xarc-react-query/test/prefetch-empty-res.ts, packages/xarc-react-query/test/spec/browser-index.spec.tsx, packages/xarc-react-query/test/spec/node-index.spec.tsx
Coverage now:
------------------|---------|----------|---------|---------|-------------------
File              | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
------------------|---------|----------|---------|---------|-------------------
All files         |     100 |    92.31 |   83.33 |     100 |                   
browser          |     100 |     87.5 |     100 |     100 |                   
index.tsx       |     100 |     87.5 |     100 |     100 | 52                
common           |     100 |      100 |       0 |     100 |                   
feature-info.ts |     100 |      100 |     100 |     100 |                   
index.ts        |     100 |      100 |       0 |     100 |                   
node             |     100 |    94.44 |     100 |     100 | …
=> add more tests for react query to increase test coverage

packages/subapp-web/lib/init.js, packages/subapp-web/src/cdn-map.js, packages/subapp-web/test/spec/init.spec.js
cdn map gets added only for deployed application. This helps in running app in standalone mode.
cc @jchip
=> pass default namespace to getBundleAssets inside cdn-map.js

packages/xarc-render-context/src/BaseOutput.ts, packages/xarc-render-context/src/MainOutput.ts, packages/xarc-render-context/src/RenderContext.ts, packages/xarc-render-context/src/RenderOutput.ts, packages/xarc-render-context/src/SpotOutput.ts, packages/xarc-render-context/src/utils.ts, packages/xarc-render-context/test/spec/render-context.spec.ts, packages/xarc-render-context/test/spec/token-module.spec.ts
fix render context lint warnings
=> fix render context lint warnings

packages/xarc-react-redux/test/spec/index.spec.tsx, packages/xarc-react-redux/test/spec/redux-shared-store.spec.ts
------------------------------|---------|----------|---------|---------|-------------------
File                          | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
------------------------------|---------|----------|---------|---------|-------------------
All files                     |   97.71 |    98.11 |   71.43 |   98.26 |                   
xarc-react-redux             |       0 |      100 |     100 |       0 |                   
.eslintrc.js                |       0 |      100 |     100 |       0 | 1-2               
xarc-react-redux/src/browser |     100 |      100 |     100 |     100 |                   
index.tsx                   |     100 |      100 |     100 |     100 |                   
xarc-react-redux/src/common  |   99.21 |    98.11 |   71.43 |     100 …
=> add more unit test to react redux

packages/xarc-react-redux/test/spec/index.spec.tsx
fix unit test error after redux code changes, covered 100% lines
------------------------|---------|----------|---------|---------|-------------------
File                    | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
------------------------|---------|----------|---------|---------|-------------------
All files               |   98.48 |    94.74 |   67.65 |     100 |                   
browser                |     100 |      100 |     100 |     100 |                   
index.tsx             |     100 |      100 |     100 |     100 |                   
common                 |   98.45 |    94.74 |   67.65 |     100 |                   
index.tsx             |   98.31 |    89.29 |   44.44 |     100 | 173,180-187       
redux-shared-store.ts |   98.57 |      100 |   93.75 …
=> fix unit test error after redux code changes

packages/xarc-subapp/test/spec/browser/client-render-pipeline.spec.ts, packages/xarc-subapp/test/spec/browser/index.spec.ts, packages/xarc-subapp/test/spec/browser/xarc-cdn-map.spec.ts, packages/xarc-subapp/test/spec/browser/xarc-subapp-v2.spec.ts, packages/xarc-subapp/test/spec/node/render-page.spec.ts, packages/xarc-subapp/test/spec/node/server-render-pipeline.spec.ts, packages/xarc-subapp/test/spec/node/start-v2.spec.ts, packages/xarc-subapp/test/spec/node/xarc-subapp-v2-node.spec.ts
----------------------------|---------|----------|---------|---------|------------------------------
File                        | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s            
----------------------------|---------|----------|---------|---------|------------------------------
All files                   |   83.13 |    73.04 |   70.13 |   83.12 |                              
browser                    |   69.19 |    47.83 |   63.27 |   69.44 |                              
client-render-pipeline.ts |   78.26 |        0 |   66.67 |   78.26 | 26-29,74                     
index.ts                  |   57.14 |       45 |   35.71 |   57.38 | 114-158                      
webpack4-jsonp.ts         |     100 |      100 |     100 |     100 | …
=> add unit test for xarc-subapp

packages/xarc-react-query/test/spec/browser-index.spec.tsx, packages/xarc-react-query/test/spec/node-index.spec.tsx, packages/xarc-webpack/package.json, packages/xarc-webpack/src/client/webpack5-jsonp-cdn.ts, packages/xarc-webpack/src/container/ContainerPlugin.ts, packages/xarc-webpack/src/container/ModuleFederationPlugin.ts, packages/xarc-webpack/src/partials/entry.ts, packages/xarc-webpack/src/partials/prod-mode.ts, packages/xarc-webpack/src/partials/subapp-chunks.ts, samples/poc-subapp-min-fastify/config/default.js, samples/poc-subapp-min-fastify/src/home/subapp-home.js, samples/poc-subapp-min-fastify/xclap.js, samples/poc-subapp/fyn-lock.yaml, samples/poc-subapp/xclap.js
webpack 5 module federation remote entry doesn't allow user to add modules to it.  So copied relevant files out and modify them directly to add CDN mapping module to remote entry.
=> enable extra module for remote entry to support CDN mapping

packages/xarc-webpack/src/partials/subapp-chunks.ts
- Allow `remotes` to be configurable
- Allow `eager` to be overridable
cc @jchip
=> Allow remotes and eager flag to be configurable as part of app config

packages/subapp-server/lib/template-routing.js
- template file can export a function that returns the template
- different routes get its own instance of the template
=> fix: subappV1 handle each route with its own template instance

packages/xarc-subapp/src/node/init-v2.ts, packages/xarc-subapp/src/node/types.ts, packages/xarc-subapp/src/node/utils.ts, packages/xarc-subapp/test/spec/node/init-v2.spec.ts
Allow users to disable nonce for script, style or both.
1. To disable nonce for both:
`nonce: false`
2. To disable nonce just for style and use default nonce settings for script:
`nonce: {
style: false
}`
3. To disable nonce just for script and use default nonce setting for style:
`nonce: {
script: false
}`
=> [fix] disable nonce for script,style or both

packages/subapp-react/lib/framework-lib.js, packages/subapp-react/test/spec/ssr-framework.spec.js
This is to support use cases like css in js e.g. Rendering Styled Components on server
e.g.  in `server` entry (server.js)
```
import {ServerStyleSheet} from "styled-components";
import ReactDOM from "react-dom/server";
export default {
renderer(element, options) {
const sheet = new ServerStyleSheet();
try {
const html = ReactDOMServer.renderToString(.  // This can be renderToNodeStream or Static markup/stream depending on option. 
sheet.collectStyles(element)
);
const styleTags = sheet.getStyleTags(); 
return styleTags + html;
} catch (error) {
console.log(error);
}
}
=> [minor][feat] add custom renderer support for SSR.

packages/xarc-jsx-renderer/package.json, packages/xarc-render-context/package.json
Temporarily fixing xaa version to 1.7.1 as the new version is breaking the jsx-renderer/xarc-render-context
=> Fix xaa version to avoid breaking change

packages/webpack-config-composer/package.json, packages/xarc-app-dev/package.json, packages/xarc-app-dev/src/lib/dev-admin/log-view.js, packages/xarc-react/test/spec/node/index.spec.tsx, packages/xarc-subapp/package.json, samples/react-jest-app/package.json, samples/stylus-sample/package.json
With typescript version 4.7.2, tests are failing in webpack-config-composer, xarc-app-dev, xarc-subapp packages. Updated the version of ts-node to fix this.
data-reactroot isn't getting created due to Context.Provider, so removed it from xarc-react test case
enzyme breaks with cheerio version v1.0.0-rc.11, so had to set cheerio to =1.0.0-rc.10 version in samples/stylus-sample, samples/react-jest-app to resolve this issue
Reference :
https://github.com/facebook/jest/issues/12655
https://github.com/facebook/react/issues/15012
https://github.com/enzymejs/enzyme/issues/2558
=> fix: update dependencies to resolve build issues

packages/xarc-webpack/package.json, packages/xarc-webpack/src/container/ModuleFederationPlugin.ts
- Manually upgraded cloned code of `ModuleFederation` plugin in `xarc-webpack` package to match Webpack's v5.74.0 update.
- Webpack minor version upgrade to v5.74.0 in `xarc-webpack` package.
=> build(minor): upgrade ModuleFederation plugin and Webpack to v5.74.0

packages/xarc-opt-sass/package.json
- Upgraded `node-sass` dependency to V7
- Upgraded `sass-loader` dependency to V13
=> [fix]: upgrade xarc-opt-sass to pass node 16 build

samples/poc-subapp-redux/package.json, samples/poc-subapp-redux/src/02.main-body/main-body.jsx, samples/poc-subapp-redux/src/02.main-body/server.jsx, samples/poc-subapp-redux/src/components/navigation.jsx, samples/poc-subapp-redux/src/subapps/03.bottom/bottom.jsx, samples/poc-subapp-redux/src/subapps/03.bottom/server.jsx, samples/poc-subapp/fyn-lock.yaml, samples/poc-subapp/package.json, samples/poc-subapp/src/02.main-body/main-body.jsx, samples/poc-subapp/src/02.main-body/server.jsx, samples/poc-subapp/src/components/navigation.jsx, samples/poc-subapp/src/subapps/03.bottom/bottom.jsx, samples/poc-subapp/src/subapps/03.bottom/server.jsx
Upgrade poc-subapp and poc-subapp-redux samples to work with React v18 and React Router v6
=> Upgrade poc-subapp and poc-subapp-redux to react18 with rr6

packages/electrode-react-webapp/package.json, packages/subapp-server/package.json, packages/subapp-server/test/spec/fastify-plugin.spec.js, packages/webpack-config-composer/package.json, packages/xarc-react-redux/package.json, packages/xarc-react-router/package.json, packages/xarc-react/package.json, packages/xarc-webpack/package.json
- Fix assertion failures due `deep-equals` package. 
A patch version bump on `chai` was causing major upgrade on `deep-equals` package. This lead to multiple failures in packages that use `deep-equal` assertions. As of now, with this PR, lock the chai version to avoid these assertion failures. This would unblock pending PRs. A better approach would be to update the assertion statement itself so that we can continue with chai upgrades in future. But since there are many such failures, deferring it to a later PR. 
- Upgrade `@types/node` to fix types issues on running `fun bootstrap`.
=> fix types issues in multiple packages

.gitignore, packages/xarc-webpack/src/partials/dev.ts, samples/poc-subapp-redux/package.json, samples/poc-subapp-redux/src/02.main-body/server.jsx, samples/poc-subapp-redux/src/04.footer/server.jsx, samples/poc-subapp-redux/src/server-routes/default/index.js, samples/poc-subapp-redux/src/subapps/03.bottom/server.jsx, samples/poc-subapp-redux/xrun-tasks.js, samples/poc-subapp/package.json, samples/poc-subapp/src/02.main-body/server.jsx, samples/poc-subapp/src/04.footer/server.jsx, samples/poc-subapp/src/subapps/03.bottom/server.jsx, samples/poc-subapp/xrun-tasks.js, samples/subapp1-online-store/package.json, samples/subapp1-online-store/src/02.main-body/server.jsx, samples/subapp1-online-store/src/03.footer/server.jsx, samples/subapp1-online-store/xrun-tasks.js
This PR includes changes to,
- Fix source-map  load warning. 
By default we are setting ``webpack`` configuration ``devtool: false``.  Looks like a recent change and we get above source-map load warning if you have dev tools open. This was causing the app to stop responding when you have dev tools open. So passing down the ``inline-source-map`` configuration through ``xrun-taslks'``s webpack configuration. 
- Setting a fallback ``devtool`` configuration to ``eval-cheap-module-source-map`` in  ``@xarc/webpack``
- Change ``clap`` references to ``xrun`` for ``poc-subapp``, `` poc-subapp-redux`` and ``subapp1-online-store``.
- Remove `bluebird` usage, instead use native ``promise`` in sample apps - ``poc-subapp``, `` poc-subapp-redux`` and ``subapp1-online-store``.  Bluebird is only need to …
=> [patch][bug] fix source map load issue

packages/xarc-opt-sass/package.json
Update node-sass and sass-loader dependencies to support node v16 installation for the @xarc/opt-sass package
=> feat(node-sass): update node-sass and sass-loader to support node v16

CHANGELOG.md, packages/xarc-opt-sass/package.json
- Changelog update for `rel-v11-20230119` (`node-sass` and `sass-loader` upgrade for node 16 compatibility)
=> chore: changelog update after opt-sass release

packages/subapp-pbundle/package.json, packages/subapp-react/package.json
Temporarily set coverage benchmark to 95% to unblock builds
=> chore: fix build failure

packages/subapp-server/test/spec/fastify-plugin.spec.js, packages/subapp-web/src/index.js, samples/poc-subapp-redux/src/components/deals.jsx
Pass props in lazyloaded subapp
=> fix: pass props to subapps through lazyloaded subapp

packages/subapp-redux/src/index.jsx
When using `reduxLoadSubapp`, the custom renderStart function is used. This custom `renderStart` is not currently handling props
Fix applied to get props from `instance` and pass it while creating root `Component`
=> [minor]: fix props passing when redux load subapp is used

packages/subapp-server/lib/fastify-plugin.js, packages/subapp-web/lib/init.js, packages/subapp-web/lib/load.js, packages/subapp-web/lib/start.js, packages/subapp-web/lib/util.js, packages/subapp-web/test/spec/load.spec.js, packages/xarc-index-page/src/token-handlers.ts, packages/xarc-index-page/test/spec/token-handler.spec.ts
Adding CSP header support for subapp v1
=> [minor] add csp feature to subappv1

common/changes/@xarc/index-page/feat-cspheader_2023-03-30-19-52.json, common/changes/subapp-server/feat-cspheader_2023-03-30-19-52.json, common/changes/subapp-web/feat-cspheader_2023-03-30-19-53.json, common/config/rush/pnpm-lock.yaml, packages/subapp-server/lib/fastify-plugin.js, packages/subapp-server/lib/utils.js, packages/subapp-web/lib/init.js, packages/subapp-web/lib/load.js, packages/subapp-web/lib/start.js, packages/subapp-web/lib/util.js, packages/xarc-index-page/src/token-handlers.ts, packages/xarc-index-page/test/spec/token-handler.spec.ts, samples/poc-subappv1-csp/src/products/subapp-products.jsx, samples/poc-subappv1-csp/src/routes.js, samples/poc-subappv1-csp/src/server/templates/template.jsx, samples/poc-subappv1-csp/src/server/token-handler.js, samples/poc-subappv1-csp/src/server/utils.js
This is an extension to https://github.com/electrode-io/electrode/pull/1958 and enforce CSP nonce for style tags
Ini addition, changes made to provide provision for users to selectively set/unset CSP for scripts and styles.
1. App can pass a generated nonce value through `cspNonce` route option
2. Set `cspNonce` flag. This would be boolean. By default `cspNonce` flag is  set `false`. Electrode will generate once and set CSP header.
3. Selectively set boolean flag for `scripts` and `styles`. Setting `cspNonce: { style: true }` will add nonce only for styles
- Sample app updated to use above approach
- Yes
=> fix: csp header with subapp v1

common/changes/@xarc/webpack/fix-cdnmap-error_2023-05-17-21-49.json, common/config/rush/pnpm-lock.yaml, packages/xarc-webpack/src/client/webpack5-jsonp-cdn.ts
Fixes a CDN map not found error when dynamic imports are used. 
`cdnMap` method was meant for non-css/js files. Fall back to the default `webpack's` public path in case of `JS` and `css`
=> fix: cdn map error when applications use dymanic imports

.github/workflows/nodejs.yml, common/config/rush/pnpm-lock.yaml, rush.json
The minimum Node.js version changed to 14.x, since 12.x have reached end-of-life.
(Even Node 14 and 16 are in end-of-life, however keeping it in our checks for some more time)
=> chore: remove node 12 as it is end of life

common/changes/@xarc/subapp/fix-stats-error_2024-01-03-22-51.json, common/changes/subapp-server/fix-stats-error_2024-01-03-22-51.json, common/changes/subapp-util/fix-stats-error_2024-01-03-22-51.json, common/config/rush/pnpm-lock.yaml, packages/subapp-server/lib/fastify-plugin.js, packages/subapp-server/lib/utils.js, packages/subapp-server/test/spec/utils.spec.js, packages/subapp-util/package.json, packages/xarc-subapp/src/node/render-page.ts, packages/xarc-subapp/src/node/utils.ts, samples/poc-subapp/package.json
Fixing stats error on initial dev server start up
=> feat: fixing stats error on initial load

common/changes/subapp-server/csp-directive_2024-03-01-04-51.json, packages/subapp-server/lib/fastify-plugin.js, packages/subapp-server/lib/utils.js, samples/poc-subappv1-csp/src/routes.js
Add ablity for applications to set their CSP headers which may include style-src & script-src. Applications can set their nonce value or use default nonce value provided by electrode as usual. 
getCSPHeader is added in route options, which accepts a function. In this function application can generate the CSP and return it as string.
=> Csp directive

common/changes/subapp-web/fix-hmr-subappV1_2024-09-06-16-32.json, packages/subapp-web/src/index.js
- Fix an issue with HMR updates
=> fix(hmr): subapp v1

common/changes/@xarc/react/fix-create-dynamic-fallback_2025-01-02-15-01.json, packages/xarc-react/src/common/create-component.tsx, samples/subapp2-poc/src/static.tsx
Use fallback component passed as props in createDynamicComponent
=> create dynamic component use fallback props
