README.md
client/components/push-notifications.jsx
package.json

PWA Features : https://github.com/donsalari/electrode-boilerplate-universal-react-node/blob/master/README.md#progressive-web-app-pwa-features-supported-by-the-electrode-framework
Push Notifications: https://github.com/donsalari/electrode-boilerplate-universal-react-node/blob/master/README.md#instructions-for-setting-up-push-notification
and 
https://github.com/donsalari/electrode-boilerplate-universal-react-node/blob/master/README.md#instructions-for-sending-a-push-notification

PWA features / Getting started with push notifications.

---

samples/universal-react-node/README.md

Fix readme multi-entry example

---

packages/electrode-archetype-react-app-dev/package.json
packages/electrode-archetype-react-app/arch-gulpfile.js
packages/electrode-archetype-react-app/config/webpack/partial/pwa.js
packages/electrode-archetype-react-app/package.json

@ananavati @Aweary @donsalari @exogen 
I think this gets us up to date with the other repo.

Sync archetype

---

samples/universal-react-node/config/default.json
samples/universal-react-node/package.json

@jchip 
This should get the react boilerplate back to working condition.

Fix sample deps

---

packages/electrode-react-webapp/lib/index.html

for issue: https://github.com/electrode-io/electrode/issues/119

add noscript tag

---

packages/generator-electrode/generators/app/index.js

With reference to : https://github.com/electrode-io/electrode/issues/166
Directory Tree for HapiJs is now clean:

Ignore unused server files.

---

packages/electrode-archetype-react-component/config/webpack/webpack.config.test.js

- modify `src` alias so that relative paths function properly

#158: modify webpack test config to allow for correct relative paths

---

samples/universal-react-node/data/storage.json
samples/universal-react-node/src/server/plugins/update-storage.js
samples/universal-react-node/src/server/storage.json
samples/universal-react-node/src/server/views/index-view.jsx

Fixing broken paths after move to `src`.

Fix Todo sample app.

---

packages/electrode-archetype-react-component/scripts/copy-as-flow-declaration.js

fixes https://github.com/electrode-io/electrode/issues/116

fix issue #116: Greedy string replace in copy-as-flow script

---

packages/generator-electrode-component/app/index.js
packages/generator-electrode-component/app/templates/_package.json

@ananavati @workingBen
With reference to issue214: https://github.com/electrode-io/electrode/issues/214
Before: 
After:

Accept different repo and package name for component generator

---

.vscode/settings.json
packages/generator-electrode-component/app/index.js
packages/generator-electrode-component/app/templates/_gulpfile.js
packages/generator-electrode-component/app/templates/demo/_demo.jsx
packages/generator-electrode-component/app/templates/eslintrc
packages/generator-electrode-component/app/templates/test/client/eslintrc
packages/generator-electrode/generators/app/index.js
packages/generator-electrode/generators/app/templates/.eslintrc
packages/generator-electrode/generators/app/templates/test/client/eslintrc
packages/generator-electrode/generators/app/templates/test/server/eslintrc

I would like the ability to use single quotes with electrode generated code.  Adding a question around if use wants to do this as well.  Then running the fix command from eslint to switch the double quotes to single quotes.

Single Quotes Question

---

packages/generator-electrode-component/app/templates/demo/_demo.jsx
packages/generator-electrode/component/templates/demo/_demo.jsx

Fix raw-loader instead of raw

---

packages/electrode-react-webapp/lib/index.html
packages/electrode-react-webapp/lib/react-webapp.js
packages/electrode-react-webapp/package.json
packages/electrode-redux-router-engine/package.json

Head tags supported:
```
<title>
<meta />
<link />
<style>
```
Body tags supported:
```
<script>
<noscript>
```

Allow dynamic head and body tags with react-helmet

---

samples/universal-react-node/config/default.json
samples/universal-react-node/package.json
samples/universal-react-node/src/client/components/home.jsx
samples/universal-react-node/src/client/components/record-form.jsx
samples/universal-react-node/src/client/components/record-store.jsx
samples/universal-react-node/src/client/routes.jsx
samples/universal-react-node/src/server/plugins/records.js

Adding an example that uses mongoDb to persist data.
- uses mongoJs to connent to mongoDb
- registered via a plugin that handles adding, fetching all or one record.

Mongo db example

---

packages/electrode-archetype-react-app-dev/config/webpack/partial/dev.js
packages/electrode-archetype-react-app/arch-gulpfile.js

Same fixes for invalid host header for oss app archetype

[WIP] invalid host header fixes for oss archetype

---

packages/electrode-archetype-react-app-dev/config/webpack/partial/pwa.js

Service worker fixes for oss archetype app

---

packages/electrode-archetype-react-app-dev/config/webpack/partial/entry.js

An entry configuration fixes for app archetype

[minor] archetype app entry configurations

---

packages/generator-electrode/README.md

minor fixes for readme

---

contributing.md
packages/generator-electrode/README.md

-Adds contributing/PR guidelines for project Readme.
-Adds an installation screen capture video for `yo electrode`.

[generator-electrode]: [chore][patch] update contributing guidelines and add demo for generator.

---

packages/electrode-archetype-react-app/arch-gulpfile.js
samples/universal-react-node/src/server/plugins/records.js

FIX gulp lint as it skips src/server files (works fine on master).
Home aoo unifying oss archetype required.

[patch][bug-fix][app-archetype] FIX gulp lint as it skips src/server files

---

packages/electrode-archetype-react-app-dev/config/webpack/partial/extract-style.js
packages/electrode-archetype-react-app-dev/package.json

Required by home app. Usage for optimize/minimize css assets.
**Before:**
**After:**
alldepartments_styles.styles.css 264KB -> 193KB
homepage_styles.styles.css 325KB ->234KB

[patch][app-archetype]A Webpack plugin to optimize / minimize CSS assets.

---

packages/electrode-archetype-react-app-dev/config/eslint/.eslintrc-mocha-test-es6

Adding a new eslint config file.

archetype-react-app-dev: [patch] [chore] add config for mocha tests with es6

---

packages/electrode-archetype-react-app/arch-gulpfile.js

`lint-server-test` task will use appropriate config based on the flag.

archetype-react-app: [patch] [chore] Modify gulp task based on flag

---

docs/chapter1/intermediate/component-archetype/README.md
docs/chapter1/intermediate/component-archetype/webpack-config.md
docs/chapter1/intermediate/create-a-electrode-component.md
docs/chapter1/quick-start/whats-inside.md

Updating electrode component archetype docs

[docs] Updating electrode component archetype docs

---

packages/generator-electrode/component/index.js

The PR is for fixing the issue:
- keep original author name
- re-construct project name and package name if user gave a space

generator-electrode: [patch][bug] Update author name and re-construct project name

---

packages/generator-electrode/component/index.js
packages/generator-electrode/generators/app/templates/_package.json
packages/generator-electrode/generators/app/templates/src/server/index.js

- Remove SSR caching from app `server/index.js`.
- update engines.
- pass keywords as an array for demo-app.

generator-electrode: [patch] [chore] remove SSR caching from app generator template.

---

packages/generator-electrode/generators/app/index.js
packages/generator-electrode/test/spec/app.spec.js

- Change question for autoSSR prompt.
- Correct value for main in `package.json` for generated app.

[patch] change autoSSR message

---

packages/electrode-archetype-react-app/arch-gulpfile.js
packages/generator-electrode/generators/app/templates/_package.json

usage
```
gulp server-devtools
gulp server-devtools-startup-breakpoint
gulp server-build-devtools
gulp server-build-devtools-startup-breakpoint
```

Debug server side components with Chrome Developer Tools (DevTools)

---

packages/electrode-archetype-react-app-dev/config/webpack/partial/extract.js
packages/electrode-archetype-react-app/arch-gulpfile.js

fixes #135 
@jchip please review

remove extractTextPlugin in hot mode

---

packages/generator-electrode/component-add/index.js
packages/generator-electrode/generators/app/index.js

- app generator: do not call git generator for the demo-app.
- add component generator: correct default for component name.

[patch] [bug] No git init for demo-app, correct default componentName.

---

docs/chapter1/intermediate/create-a-electrode-component/add-to-demo-app.md
docs/chapter1/intermediate/create-a-electrode-component/component-generator-setup.md
docs/chapter1/intermediate/create-a-electrode-component/component-helpers.md
docs/chapter1/intermediate/create-a-electrode-component/develop-main-component.md
docs/chapter1/intermediate/create-a-electrode-component/develop-styles.md
docs/chapter1/intermediate/create-a-electrode-component/low-level-components.md
docs/chapter1/intermediate/create-a-electrode-component/test-components.md

- Update name "your-awesome-component" to "your-component"
- use prop-types
- fix the npm test issues

gitbook: [patch][bug] Update docs

---

packages/generator-electrode/generators/app/templates/src/server/index.js

https://github.com/electrode-io/electrode/issues/456

[patch] fix dangling comment in generated app

---

docs/chapter1/intermediate/create-a-electrode-component/component-generator-setup.md
docs/chapter1/intermediate/create-a-electrode-component/what-is-inside.md
docs/chapter1/quick-start/build-component.md

Changes included:
- update `Build Component` section in `Quick Start` since the initial `Get Started` section `yo electrode` generate app has been updated. And `Build Component` is a continues work based on `Get Started` section.
- Update docs for latest electrode component structure (demo folder)
Changes verified on my local.

[patch][chore] Update docs for latest electrode component

---

packages/generator-electrode/component/index.js

Add `components.md` in component generator for electrode explorer "View Doc" section.

[patch][feat] add components.md to component generator

---

docs/overview/what-is-electrode.md

Spell mistake - Sacling -> Scaling

Spell mistake - Sacling -> Scaling

---

.vscode/settings.json
package.json

Also, rearranged package.json from most frequently needed information to least.

[patch] [chore] removed vscode plugin settings

---

docs/chapter1/quick-start/start-with-component.md

Update docs for component-add generator when overwrites happened.

[patch] Update docs for generator component-add

---

packages/electrode-archetype-react-component-dev/config/karma/browser-settings.js
packages/electrode-archetype-react-component-dev/config/karma/karma.conf.dev.js
packages/electrode-archetype-react-component-dev/config/karma/karma.conf.js
packages/electrode-archetype-react-component-dev/package.json
packages/electrode-archetype-react-component/config/archetype.js

A chrome headless adding to component archetype

[patch][feat] Add chrome headless to component archetype

---

docs/overview/requirements.md

Update headless chrome set up docs

[patch][feat] Update headless chrome set up docs

---

packages/generator-electrode/component/templates/packages/component/src/components/_accordion.jsx
packages/generator-electrode/component/templates/packages/component/src/components/_component.jsx

Fixes for component generator 
- eslint error: max-len 
- eslint warning: Handler function for onClick prop key must begin with 'handle'

[patch][bug] Fixes for eslint error: max-len and eslint warning: Handler function for onClick prop key must begin with 'handle'

---

packages/electrode-archetype-react-app/FAQ.md
packages/electrode-archetype-react-component/FAQ.md
packages/electrode-archetype-react-component/README.md

Update component archetype README

[patch][chore] Update Readme component archetype

---

packages/electrode-react-webapp/lib/express/index.js
packages/electrode-react-webapp/lib/group-scripts.js
packages/electrode-react-webapp/lib/hapi/index.js
packages/electrode-react-webapp/lib/http-status.js
packages/electrode-react-webapp/lib/koa/index.js
packages/electrode-react-webapp/lib/render-output.js
packages/electrode-react-webapp/package.json
packages/electrode-react-webapp/test/spec/express.index.spec.js
packages/electrode-react-webapp/test/spec/hapi.index.spec.js
packages/electrode-react-webapp/test/spec/koa.index.spec.js

This is an updated version with 100% Test coverage of this PR: https://github.com/electrode-io/electrode/pull/580

Keep custom status codes better coverage

---

packages/electrode-ignite/cli/ignite.js
packages/ignite-core/lib/prompt-menu.js

- strict mode
- only log title with a valid command

[patch] fix argument parsing

---

packages/generator-electrode/component/index.js
packages/generator-electrode/component/templates/packages/component/src/components/_component.jsx
packages/generator-electrode/component/templates/packages/component/test/client/components/_component.spec.jsx
packages/generator-electrode/generators/app/index.js

- Fixes incorrect template copying in component generator
- Fixes tests in generated component.

[patch][bug] Fix component generator

---

packages/electrode-ignite/lib/do-yo.js
packages/electrode-ignite/lib/menu-items/electrode-oss-doc.js
packages/electrode-ignite/test/spec/do-yo.spec.js
packages/electrode-ignite/test/spec/menu-items/electrode-oss-doc.spec.js

- yopath for generators accept params for base
- gitbook accept params for wml link
- update unit test
- fixed a hanging case when child process exit its own for any reason

[minor] Changes for wml electrode-ignite

---

packages/electrode-archetype-react-app-dev/config/karma/karma.conf.coverage.js
packages/electrode-archetype-react-app-dev/config/karma/karma.conf.js
packages/electrode-archetype-react-app-dev/package.json

Based on https://gecgithub01.walmart.com/R-Discovery/discovery-archetype-react-app/pull/21

[minor] Add sonarQubeUnitReporter to Karma test coverage output

---

docs/overview/what-is-electrode.md

Link to Electrode Archetype System in the overview section was updated.

Fix documentation link

---

packages/electrode-archetype-react-app-dev/config/karma/entry.js
packages/electrode-archetype-react-app-dev/package.json

[patch] add enzyme adapter config for tests in React 16

---

packages/electrode-ignite/package.json

lerna doesn't detect major bump of a dependency

[major] mark for update on major bump of generator

---

packages/electrode-archetype-react-app-dev/config/babel/babelrc-client
packages/electrode-archetype-react-app-dev/config/webpack/partial/babel.js
packages/electrode-archetype-react-app-dev/package.json

Fix the issue for `react-hot-loder`
Issue: https://github.com/gaearon/react-hot-loader/issues/643
Solution: Based on https://github.com/gaearon/react-hot-loader#getting-started
Upgrade `react-hot-loader` to v3
Verified on
Home App

[patch][archetype-app] resolve react/lib/ReactMount issue for hot reload

---

packages/electrode-webpack-reporter/lib/webpack-reporter.js
packages/electrode-webpack-reporter/src/client/components/navbar.jsx

- fix the reload page, `cannot get` issue
- fix the reload page, selected tab missing issue

[patch]Webpack reporter fixes

---

.gitignore

TBD on what to do with lock files, ignore for now.

ignore lock files

---

packages/generator-electrode/component/templates/demo-app/src/client/components/home.jsx

A bug when running `npm run test` form newly generated component's demo-app folder from generator.

[patch] fix eslint error in demo-app of generated component

---

samples/demo-component/demo-app/archetype/config/webpack/webpack.config.dev.js
samples/demo-component/demo-app/archetype/config/webpack/webpack.config.js
samples/demo-component/demo-app/package.json
samples/demo-component/package.json
samples/demo-component/packages/demo-component/package.json
samples/demo-component/packages/demo-component/src/components/AppBarExampleIconMenu.jsx
samples/demo-component/packages/demo-component/src/components/CardExampleWithAvatar.jsx
samples/demo-component/packages/demo-component/test/client/components/helpers/intl-enzyme-test-helper.js

[major] update sample demo component to React 16

---

samples/demo-component/demo-app/archetype/config/webpack/webpack.config.dev.js
samples/demo-component/demo-app/archetype/config/webpack/webpack.config.js
samples/demo-component/demo-app/src/client/app.jsx
samples/demo-component/demo-app/src/client/components/home.jsx
samples/demo-component/packages/demo-component/demo/demo.css
samples/demo-component/packages/demo-component/demo/demo.jsx
samples/demo-component/packages/demo-component/demo/examples/demo-component.example
samples/demo-component/packages/demo-component/package.json

This PR requires a merge and release of new oss component archetpe (with major bump for demo-index) https://github.com/electrode-io/electrode/pull/711

[minor] Consumes component from demo folder

---

packages/electrode-webpack-reporter/src/client/styles/inline-styles.js

[patch] Webpack reporter text overflow issue

---

packages/electrode-archetype-react-component-dev/package.json

which has dependency on react 15

removing deprectated electrode-demo-index

---

packages/electrode-react-webapp/index.js
packages/electrode-react-webapp/lib/hapi/index.js
packages/electrode-react-webapp/package.json
packages/electrode-react-webapp/test/spec/express.index.spec.js
packages/electrode-react-webapp/test/spec/hapi.index.spec.js

first of some updates.
New feature planned:
- Support dynamically switching the index.html template base on incoming request parameters etc
@romanlv @didi0613 @datvong-wm

export a main for package.json

---

samples/universal-react-node/_test_/client/.babelrc
samples/universal-react-node/_test_/client/components/home.spec.jsx
samples/universal-react-node/test/client/components/home.spec.jsx
samples/universal-react-node/test/client/sw-events.js

Add jest tests to sample app.
This PR requires: https://github.com/electrode-io/electrode/pull/775

add jest test to sample app

---

packages/generator-electrode/generators/app/templates/src/client/components/home.jsx

fix https://github.com/electrode-io/electrode/issues/804

use span to avoid inconsistent spaces

---

packages/electrode-webpack-reporter/src/client/styles/base.css

[bug][patch] fix webpack reporter text overflow issue

---

packages/electrode-archetype-react-component-dev/config/webpack/partial/extract-style.js

fix a small typo

---

packages/electrode-react-webapp/.babelrc
packages/electrode-react-webapp/lib/react/token-handlers.js
packages/electrode-react-webapp/package.json
packages/electrode-react-webapp/test/router-engine/content.jsx
packages/electrode-react-webapp/test/router-engine/routes.jsx
packages/electrode-react-webapp/test/spec/hapi.index.spec.js

fix https://github.com/electrode-io/electrode/issues/862

fix 302 redirect from router engine

---

docs/README.md
docs/overview/what-is-electrode.md

[patch] fix links for overview and readme section

[patch] fix links for overview and readme section

---

packages/electrode-react-webapp/lib/hapi/index.js
packages/electrode-react-webapp/test/spec/hapi.index.spec.js

When an error occur, it helps with debugging to reply with the error stack

default to reply with error stack

---

packages/generator-electrode/generators/app/templates/_package.js
packages/generator-electrode/generators/config/templates/default.js

[patch] Add Hapi good/good-console logger to the generator Hapi app

---

packages/electrode-ignite/lib/do-yo.js

Tested on windows with user name: "di di"
Related Issue: https://github.com/electrode-io/electrode/issues/812

[patch] fix ignite generator invoking to support windows user dir with space

---

packages/electrode-redux-router-engine/lib/redux-router-engine.js
packages/electrode-redux-router-engine/test/routes.jsx
packages/electrode-redux-router-engine/test/spec/redux-router-engine.spec.js

[minor] [bug] Fix methods prop in route definition not being respected

---

packages/electrode-react-webapp/lib/hapi/index.js
packages/electrode-react-webapp/lib/react-webapp.js
packages/electrode-react-webapp/lib/render-output.js
packages/electrode-react-webapp/test/spec/hapi.index.spec.js
packages/electrode-react-webapp/test/spec/render-output.spec.js

- How content can be defined for each path has been cumulatively evolving such that there are different specs.
- Clarify all scenarios and handle them properly.

clarify content spec for paths

---

packages/electrode-archetype-react-app-dev/config/archetype.js
packages/electrode-archetype-react-app-dev/config/webpack/partial/extract-style.js

apply the same https://github.com/electrode-io/electrode/pull/922 for v4 branch

update optimize css to not touch zindex by default

---

packages/electrode-archetype-react-app-dev/.eslintignore
packages/electrode-archetype-react-app-dev/lib/module-processor.js
packages/electrode-archetype-react-app-dev/lib/webpack-dev-hapi.js
packages/electrode-archetype-react-app-dev/package.json
packages/electrode-archetype-react-app-dev/test/.eslintrc
packages/electrode-archetype-react-app-dev/test/mocha.opts
packages/electrode-archetype-react-app-dev/test/spec/extract.style.spec.js
packages/electrode-archetype-react-app-dev/xclap.js

extract-style.js                                                     |      100 |      100 |      100 |      100 |                   |

[patch] add unit tests for extract-styles.js

---

packages/electrode-archetype-react-app-dev/test/spec/extract.style.spec.js

extract-style.js                                                     |      100 |      100 |      100 |      100 |                   |

[patch] add unit tests for optional sass

---

packages/electrode-archetype-react-app-dev/config/archetype.js
packages/electrode-archetype-react-app-dev/config/webpack/partial/extract-style.js
packages/electrode-archetype-react-app-dev/package.json

new xenv-config 1.3.0 support json type.
update archetype config to use it.

update xenv-config to 1.3.0 with json type support

---

packages/electrode-archetype-opt-sass/optional-check.js
packages/electrode-archetype-react-app-dev/config/webpack/partial/extract-style.js
packages/electrode-archetype-react-app-dev/test/spec/extract.style.spec.js

fix turning off sass cause app build to fail.

fix optional node-sass

---

packages/webpack-config-composer/lib/index.js

fix https://github.com/electrode-io/electrode/issues/948

[bug] safe access addopt

---

packages/electrode-archetype-webpack-dll-dev/config/archetype.js
packages/electrode-archetype-webpack-dll-dev/config/webpack/partial/define.js
packages/electrode-archetype-webpack-dll-dev/config/webpack/partial/dll.js
packages/electrode-archetype-webpack-dll-dev/config/webpack/partial/entry.js
packages/electrode-archetype-webpack-dll-dev/config/webpack/partial/index.js
packages/electrode-archetype-webpack-dll-dev/config/webpack/partial/optimize.js
packages/electrode-archetype-webpack-dll-dev/config/webpack/partial/output.js
packages/electrode-archetype-webpack-dll-dev/config/webpack/partial/resolve.js
packages/electrode-archetype-webpack-dll-dev/config/webpack/partial/stats.js
packages/electrode-archetype-webpack-dll-dev/config/webpack/profile.base.js
packages/electrode-archetype-webpack-dll-dev/config/webpack/util/context.js
packages/electrode-archetype-webpack-dll-dev/config/webpack/util/generate-config.js
packages/electrode-archetype-webpack-dll-dev/config/webpack/webpack.config.dev.js
packages/electrode-archetype-webpack-dll-dev/package.json
packages/electrode-archetype-webpack-dll-dev/require.js
packages/electrode-archetype-webpack-dll-dev/test/fixtures/dll-test/index.js
packages/electrode-archetype-webpack-dll-dev/test/mocha.opts
packages/electrode-archetype-webpack-dll-dev/test/spec/config-webpack.spec.js
packages/electrode-archetype-webpack-dll-dev/xclap.js
packages/electrode-archetype-webpack-dll/arch-clap-tasks.js
packages/electrode-archetype-webpack-dll/config/archetype.js
packages/electrode-archetype-webpack-dll/package.json
packages/electrode-archetype-webpack-dll/test/fixtures/save-cdn-map/cdn-assets.json
packages/electrode-archetype-webpack-dll/test/mocha.opts
packages/electrode-archetype-webpack-dll/test/spec/arch-clap.spec.js
packages/electrode-archetype-webpack-dll/xclap.js

archetype to support creating modules that are webpack DLL for sharing between apps.

first commit - webpack dll archetype

---

packages/electrode-archetype-opt-karma/package.json

This reverts commit 3fa3f28401b2d2a80ffa058d96f2e138922adeb9.

Revert "update karma for webpack4 (#968)"

---

packages/electrode-archetype-react-app-dev/config/webpack/partial/dev.js
packages/electrode-archetype-react-app-dev/config/webpack/partial/extract-style.js
packages/electrode-archetype-react-app-dev/config/webpack/partial/uglify.js

Followed instructions: https://developers.google.com/web/fundamentals/performance/webpack/decrease-frontend-size

[major] Webpack 4: decrease front end size

---

packages/electrode-archetype-react-app-dev/config/webpack/partial/extract-style.js

enable minimize in css loader level.

Webpack4 update extract styles

---

packages/electrode-archetype-react-app/arch-clap.js

referring to ticket: https://jira.walmart.com/browse/CEECORE-431

[patch] add display error details to show a more detailed breakdown of why an error occurs

---

packages/electrode-archetype-react-app-dev/config/webpack/partial/dll-load.js
packages/electrode-archetype-webpack-dll-dev/lib/save-module-versions.js

- remember the exact path a library was installed under node_modules for the DLL package
- and expect app to have the same version of the same lib installed in the same location
> This restriction is brittle and unfortunate but that's how webpack DLL work.
> Mitigating idea: detect and locate the actual dir a package@version is installed and update DLL's manifest.

more sophisticated DLL library version check

---

packages/electrode-archetype-react-app-dev/test/spec/extract.style.spec.js

[patch] Fix electrode archetype react app dev extract-styles tests

---

packages/electrode-ignite/xclap.js
packages/generator-electrode/xclap.js

Make the electrode-ignite and generator-electrode that's updated for the v6 a major release.

[major] touch to update for v6

---

packages/electrode-archetype-react-app-dev/package.json

https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/issues/172

lock version to resolve upstream issue

---

packages/electrode-archetype-react-app-dev/lib/fake-res.js
packages/electrode-archetype-react-app-dev/lib/webpack-dev-hapi17.js

https://github.com/hapijs/hapi/issues/3884

more hapi17 fix for dev middleware

---

samples/universal-react-node/package.json
samples/universal-react-node/src/client/styles/base.css

demo solution for https://github.com/electrode-io/electrode/issues/1077

demo CSS @import from node_modules

---

packages/electrode-archetype-react-app-dev/lib/fake-res.js
packages/electrode-archetype-react-app-dev/lib/webpack-dev-express.js
packages/generator-electrode/generators/app/templates/src/server/express-server.js
xclap.js

fix https://github.com/electrode-io/electrode/issues/1104

[patch][bug] fix webpack-dev-express middleware setup

---

packages/electrode-react-webapp/lib/hapi/plugin16.js
packages/electrode-react-webapp/lib/index.html
packages/electrode-react-webapp/lib/react/token-handlers.js
packages/electrode-react-webapp/test/spec/hapi.index.spec.js
packages/electrode-react-webapp/test/spec/hapi17.index.spec.js
packages/generator-electrode/generators/app/templates/_package.js
packages/generator-electrode/generators/app/templates/src/client/components/home.jsx
packages/generator-electrode/generators/config/templates/hapijs/default.js
xclap.js

https://github.com/electrode-io/electrode/issues/508

add handling and demo for using electrode-ui-config

---

packages/electrode-archetype-react-app/lib/app-mode.js

https://github.com/electrode-io/electrode/issues/1120

[patch][bug] ensures app mode dir always use /

---

packages/electrode-archetype-react-app-dev/config/archetype.js
packages/electrode-archetype-react-app-dev/config/babel/babelrc-client.js
packages/electrode-archetype-react-app-dev/config/webpack/partial/output.js

1 fix output `dist-default` 
2 add default `target` to babel config

fix output `dist-X` issue

---

packages/electrode-archetype-react-app-dev/lib/webpack-dev-express.js
packages/electrode-archetype-react-app-dev/lib/webpack-dev-koa.js

fix `process.send` undefined issue, according to https://github.com/electrode-io/electrode/issues/1198

fix `process.send` issue

---

docs/chapter1/over-the-air/react-native-and-over-the-air.md

3 images weren't being displayed because they were invalid URLs

Fix broken image URLs

---

packages/electrode-archetype-react-app-dev/config/webpack/partial/entry.js
packages/electrode-archetype-react-app-dev/config/webpack/partial/extract-style.js
packages/electrode-archetype-react-app-dev/config/webpack/partial/uglify.js

following https://github.com/electrode-io/electrode/pull/1197

fix entry format with enableBabelPolyfill as true for archetype@5

---

packages/electrode-archetype-react-app-dev/config/archetype.js
packages/electrode-archetype-react-app-dev/config/webpack/partial/index.js
packages/electrode-archetype-react-app-dev/config/webpack/partial/terser.js
packages/electrode-archetype-react-app-dev/config/webpack/partial/uglify.js
packages/electrode-archetype-react-app-dev/config/webpack/webpack.config.js
packages/electrode-archetype-react-app-dev/package.json

install `terser-webpack-plugin-legacy` to archetype v5 and add partial/terser.js.
set minifier by `archetype.webpack.minifier` as `uglify` or `terser`

add partial/terser

---

packages/electrode-archetype-react-app-dev/config/webpack/partial/extract-style.js
packages/electrode-archetype-react-app-dev/lib/dev-admin/middleware.js

fix the subsequent request under https://github.com/electrode-io/electrode/issues/1255

enable styles HMR

---

packages/electrode-archetype-react-app-dev/config/webpack/partial/extract-style.js
packages/electrode-archetype-react-app-dev/package.json

* Bump AutoPrefixer to latest 9.6.0
* Use overrideBrowserslist option

Bump AutoPrefixer version to 9.6.0 (#1)

---

packages/electrode-archetype-react-app-dev/config/webpack/partial/extract-style.js
packages/electrode-archetype-react-app-dev/config/webpack/partial/fonts.js

revert PR https://github.com/electrode-io/electrode/pull/1261

[bug] revert style and font publicPath

---

packages/electrode-archetype-react-app-dev/config/archetype.js
packages/electrode-archetype-react-app-dev/config/babel/babelrc-client.js
packages/electrode-archetype-react-app-dev/config/webpack/partial/loadable.js

+ set a flag for dynamic import babel setup and webpack plugins
+ fix missing chunks for dynamic import syntax

[feat] add `enableDynamicImport` to archetype

---

packages/generator-electrode/generators/app/index.js

+ **after other optional features**
+ **inspect variable name**

[feat] update app generator for optional features

---

.vscode/launch.json
packages/electrode-archetype-react-app/arch-clap.js
packages/electrode-ignite/README.md
packages/generator-electrode/component/index.js
packages/generator-electrode/component/templates/demo-app/src/client/components/home.jsx
packages/generator-electrode/component/templates/packages/component/_package.json
packages/generator-electrode/generators/app/index.js

Fix demo-app
Move .babelrc.js under src to babel.config.js in project root.

Fix component demo app

---

packages/subapp-server/lib/hapi-plugin.js
packages/subapp-server/lib/utils.js
packages/subapp-server/package.json
packages/subapp-server/test/spec/utils.spec.js
samples/poc-subapp/fyn-lock.yaml

- drop hapi@16
- add `srcDir`, `loadRoutesFrom` to plugin options

update hapi plugin options and drop v16 support

---

packages/electrode-archetype-react-app-dev/config/webpack/partial/dll-reference.js
packages/electrode-archetype-react-app-dev/config/webpack/util/detect-css-module.js
packages/electrode-archetype-react-app-dev/package.json
packages/electrode-archetype-react-app-dev/scripts/merge-isomorphic-assets.js
packages/electrode-archetype-react-app/arch-clap.js

should merge after https://github.com/electrode-io/electrode/pull/1355

use filter-scan-dir over glob

---

packages/electrode-archetype-react-app-dev/config/archetype.js
packages/electrode-archetype-react-app-dev/config/webpack/partial/extract-style.js
packages/electrode-archetype-react-app/arch-clap.js

should merge after https://github.com/electrode-io/electrode/pull/1357

fix css module detection

---

samples/hapi-app/archetype/config/index.js
samples/hapi-app/fyn-lock.yaml
samples/hapi-app/src/client/components/demo-cookies.jsx
samples/hapi-app/src/client/components/home.jsx
samples/hapi-app/src/client/styles/demo3.less

should merge after https://github.com/electrode-io/electrode/pull/1358

less style demo sample

---

packages/electrode-archetype-opt-postcss/package.json
packages/electrode-archetype-react-app-dev/package.json
samples/hapi-app/fyn-lock.yaml
samples/hapi-app/src/client/components/demo-sugarss.jsx
samples/hapi-app/src/client/components/home.jsx
samples/hapi-app/src/client/styles/custom-sugarss.styl
samples/hapi-app/test/client/.babelrc
samples/hapi-app/test/server/.babelrc
samples/universal-react-node/fyn-lock.yaml

- Verified sugarss dependency in electrode-archetype-opt-postcss
- Created a new demo ( copying Demo 2 ) but using *.styl instead of css to verify that it works.

Ceecore 961

---

samples/react-jest-app/README.md
samples/universal-material-ui/README.md

fixed https://github.com/electrode-io/electrode/issues/1412

fix typo for xclap-cli

---

packages/electrode-archetype-react-app-dev/config/webpack/partial/extract-style.js
packages/electrode-archetype-react-app-dev/config/webpack/partial/output.js
packages/electrode-archetype-react-app-dev/config/webpack/partial/pwa.js
packages/electrode-archetype-react-app-dev/config/webpack/partial/test-output.js

CEECORE-965: Replace webpack [hash] with [contenthash]

---

packages/electrode-archetype-react-app-dev/lib/app-dev-middleware.js

notify dev-admin app server started ASAP

---

packages/electrode-archetype-react-app-dev/lib/dev-admin/console-io.js

fix https://github.com/electrode-io/electrode/issues/1461

dev admin only read keys in TTY mode

---

packages/electrode-archetype-react-app-dev/lib/dev-admin/dev-fastify.js
packages/electrode-archetype-react-app-dev/test/spec/dev-admin/dev-fastify.spec.js

In electrode-archetype-react-app-dev, Add dev-admin module for fastify server.

react-app-dev: Add dev-admin for fastify

---

packages/subapp-web/lib/load.js
packages/subapp-web/lib/util.js
samples/poc-subapp-pmin/archetype/config/index.js
samples/poc-subapp-pmin/package.json
samples/poc-subapp-pmin/src/home/subapp-home.js

A first pass at fixing loading CSS bundles for subapps.  
Original loading code only deal with JS bundles and that code could use some refactoring to treat bundles more generically.

handles css bundles for subapps

---

packages/subapp-pbundle/src/redux-bundler.jsx
packages/subapp-pkg-util/babelrc.js
packages/subapp-pkg-util/xclap.js
packages/subapp-web/src/index.js
packages/subapp-web/src/subapp-web.js

Add new functions for subapps: waitForSubApp, isLoaded

Prepare data before invoking SSR'ed subapp that's inlined

---

packages/subapp-pbundle/lib/framework-lib.js
packages/subapp-pbundle/package.json
packages/subapp-pbundle/src/redux-bundler.jsx
packages/subapp-pbundle/src/shared.js
packages/subapp-pbundle/test/spec/fe-framework.spec.js
packages/subapp-pbundle/test/spec/shared.spec.js
packages/subapp-pbundle/test/spec/ssr-framework.spec.js
packages/subapp-pkg-util/babelrc.js
packages/subapp-web/lib/load.js
packages/subapp-web/lib/start.js
packages/subapp-web/package.json
packages/subapp-web/src/index.js
packages/subapp-web/src/subapp-web.js
packages/subapp-web/test/spec/async-map.spec.js
samples/poc-subapp-pbx/src/group-1-a/server.js
samples/poc-subapp-pbx/src/group-1-b/server.js
samples/poc-subapp-pbx/src/home/server.js
samples/poc-subapp-pbx/src/home/subapp-home.js
samples/poc-subapp-pbx/src/routes.js
samples/poc-subapp/src/components/deals.jsx

Now subapp inlining works both SSR and CSR
- changes to `subApp.start`
```js
subApp.start(instance, options, info)
```
If `instance` is unknown, then pass `null` for it.

collect all bundles and initial states before creating real redux store

---

packages/xarc-app-dev/config/webpack/partials/subapp-chunks.js

Common should only include well-shared code

Increase minChunks to 10 for MINIMIZE_SUBAPP_CHUNKS

---

packages/xarc-app-dev/lib/dev-admin/log-parser.js
packages/xarc-app-dev/test/spec/dev-admin/log-parser.spec.js

Debugger messages marked as "warn" (shown in console)

---

packages/xarc-app/lib/features.js
packages/xarc-app/test/spec/features.spec.js

This is a resolution for #1546

Hardcode the optional features for the features task

---

packages/subapp-pbundle/src/shared.js
packages/subapp-pbundle/test/spec/shared.spec.js

Prevent integrateBundles from being used with existing bundles

Use composeBundlesRaw instead of composeBundles

---

packages/electrode-react-webapp/lib/render-output.js
packages/electrode-react-webapp/test/spec/render-output.spec.js
packages/subapp-server/lib/register-routes.js
packages/subapp-server/package.json
packages/subapp-util/lib/index.js
packages/subapp-util/package.json
packages/subapp-web/lib/load.js
packages/subapp-web/lib/util.js
packages/xarc-app-dev/lib/dev-admin/admin-server.js

- Need to allow app to control streaming
- detect that stringify could fail
- avoid logging the entire error in dev mode if can't load CDN assets
- default CDN to off

Various fixes

---

.github/ISSUE_TEMPLATE/bug_report.md

collecting stats can be tedious
automate it!

docs(github): one-command solution for collecting system stats

---

packages/create-app/package.json
packages/create-app/src/check-dir.js
packages/create-app/src/create.js
packages/create-app/src/sort-obj-keys.js
packages/create-app/template/README.md
packages/create-app/template/_gitignore
packages/create-app/template/_package.js
packages/create-app/template/src/server/index.js

- update template's deps
- fix passing lodash to template's code during generation
- switch to fastify

update: create-app templates and dep

---

README.md

[patch][bug] Fix the broken contribution link

---

packages/electrode-node-resolver/lib/node-resolver.js

new node.js with ESM forbids requiring anything (including package.json) that are not specified as exports.

fix: handle new node.js ESM quirks

---

packages/xarc-app-dev/src/config/jest/jest.config.ts

Support automatic enzyme configuration for Jest above version 24.

---

packages/xarc-react-query/test/spec/browser-index.spec.ts

added unit test for react query browser side

[minor][chore]added unit test for react query browser side

---

packages/xarc-react-router/package.json
packages/xarc-react-router/test/spec/browser-index.spec.tsx
packages/xarc-react-router/test/spec/node-index.spec.tsx

test coverage:
---------------------------|---------|----------|---------|---------|-------------------
File                       | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
---------------------------|---------|----------|---------|---------|-------------------
All files                  |     100 |       90 |     100 |     100 |                   
browser                   |     100 |    92.86 |     100 |     100 |                   
index.ts                 |     100 |      100 |     100 |     100 |                   
react-router-browser.tsx |     100 |    92.86 |     100 |     100 | 43                
common                    |     100 |      100 |     100 |     100 |                   
index.ts                 |     100 |      100 |     100 |     100 | …

add unit tests for xarc react router

---

samples/subapp2-react-query-todoapp/src/todo/component/todo-input.tsx
samples/subapp2-react-query-todoapp/src/todo/component/todo.tsx
samples/subapp2-react-query-todoapp/src/todo/component/todoapp.tsx
samples/subapp2-react-query-todoapp/src/todo/component/visibility-filters.tsx
samples/subapp2-react-query-todoapp/src/todo/mock-fetch.ts

add checkbox on todo
remove unnecessary states

refactor react query todo app

---

samples/subapp2-react-query-todoapp/src/todo/component/todo-input.tsx
samples/subapp2-react-query-todoapp/src/todo/component/todo.tsx
samples/subapp2-react-query-todoapp/src/todo/component/todoapp.tsx
samples/subapp2-react-query-todoapp/src/todo/component/visibility-filters.tsx
samples/subapp2-react-query-todoapp/src/todo/mock-fetch.ts
samples/subapp2-todo-app/src/todo/component/todo-input.tsx
samples/subapp2-todo-app/src/todo/component/todo.tsx
samples/subapp2-todo-app/src/todo/component/todoapp.tsx

Refactor subapp2 todo app:
1.add checkbox;
2.support for enter on input;
3.add more margin

Refactor subapp2 todo app

---

packages/xarc-react-redux/.eslintrc.js
packages/xarc-react-redux/src/common/index.tsx
packages/xarc-react-redux/src/common/redux-shared-store.ts
packages/xarc-react-redux/test/spec/index.spec.tsx
packages/xarc-react-redux/test/spec/redux-shared-store.spec.ts

fix react redux lint warnings

---

packages/xarc-app-dev/src/lib/dev-admin/admin-server.ts
packages/xarc-app-dev/src/lib/dev-admin/log-parser.ts
packages/xarc-app-dev/src/lib/dev-admin/log-view.js
packages/xarc-app-dev/src/lib/dev-admin/log.html

1. Remove the unnecessary meta info inside log,
2. show the original JSON,
3.Having two columns, first column showing meta info and it can be displayed or hided by users.

improve log viewer ui/ux

---

packages/xarc-app-dev/src/lib/dev-admin/log-view.js
packages/xarc-app-dev/src/lib/dev-admin/log.html

Add button at log viewer page to turn on/off log's JSON prettier.

Json pretty on off

---

packages/subapp-server/lib/fastify-plugin.js
packages/subapp-server/lib/routes-from-file.js
packages/subapp-server/lib/setup-hapi-routes.js
packages/subapp-server/test/data/fastify-plugin-test/demo3/app.js
packages/subapp-server/test/data/fastify-plugin-test/demo3/server.js
packages/subapp-server/test/data/fastify-plugin-test/demo3/subapp-manifest.js
packages/subapp-server/test/spec/fastify-plugin.spec.js
packages/subapp-server/test/spec/setup-hapi-routes.spec.js

This can act as hook to enrich server with new routes, plugins, lifecycle hooks etc.

Add hook for initializing subapp Server code

---

packages/subapp-react/lib/framework-lib.js
packages/subapp-react/test/spec/ssr-framework.spec.js

Serialize server's prepare data to client for hydration

---

packages/xarc-app-dev/src/lib/stats-utils.ts

Fix broken link: `http://localhost:3000/__electrode_dev/reporter`

Fix broken reporter link

---

fyn-lock.yaml
samples/poc-subapp/fyn-lock.yaml
samples/poc-subapp/xrun-tasks.js
samples/subapp2-poc/package.json
samples/subapp2-poc/src/declarations.d.ts
samples/subapp2-poc/src/home.tsx
samples/subapp2-poc/src/server/index.tsx
samples/subapp2-poc/src/styles/custom.module.css

- Fix eager consumption error in sample application - `poc-subapp`
- Fix incorrect routing in `subapp2-poc`
- Upgrade packages in sample apps to keep it up-to-date

fix: sample applications

---

common/changes/rush-package-test/validate-publish_2023-01-12-23-34.json
common/config/rush/pnpm-lock.yaml
packages/rush-package-test/src/index.js
rush.json

This is a test PR to verify rush publish operation.
Developer contribution flow 
- Make code changes
- Run ` rush change --target-branch <targetBranch>`  This checks for updates to ``targetBranch``. It will show interactive messages on command line and ask you to add change details. This will generates change files.
- Push PR (with changes similar to what we have in this PR). Note the file `common/changes/rush-package-test/validate-publish_2023-01-12-23-34.json`

chore: testing package publish flow

---

packages/electrode-archetype-webpack-dll-dev/config/webpack/util/generate-config.js
packages/electrode-archetype-webpack-dll/config/archetype.js

This is a dummy PR to bump up the versions for electrode-dll packages as we had a webpack upgrade in one of the previous PRs

major: commit to bump up webpack versions

---

packages/electrode-archetype-webpack-dll-dev/lib/save-module-versions.js
packages/electrode-archetype-webpack-dll/config/archetype.js

- small commit to bump up dll packages major versions due to webpack version upgrades in previous commit - https://github.com/electrode-io/electrode/pull/1917

[major] small commit to bump up dll packages major versions due to webpack version upgrades in previous commits

---

packages/xarc-opt-sass/package.json

Upgrade node-sass  and sass loader package  to support node v16 and above
https://github.com/electrode-io/electrode/pull/1936

[major] node-sass upgrade for node v16 and above

---

packages/xarc-opt-sass/package.json

fix upgrade node-sass and sass-loader dependencies

[minor] fix sass-loader and node-sass

---

packages/xarc-opt-sass/package.json

[minor] node-sass replaced with sass

---

.github/workflows/nodejs.yml
rush.json

Update workflow and rush to use Node 18

chore: Node18 update

---

common/config/rush/pnpm-lock.yaml
samples/poc-subappv1-csp/src/routes.js
samples/poc-subappv1-csp/src/server/templates/template.jsx

Some comment update in sample app to explain its usage properly

chore: fix sample application with csp header

---

common/changes/@xarc/index-page/fix-cspError_2023-05-09-20-50.json
packages/xarc-index-page/src/token-handlers.ts

This includes change files to release fix for CSP nonce error

fix: release csp error due to missing default csp nonce value

---

common/changes/@xarc/webpack/revert-cdnmapfix_2023-06-07-19-16.json
common/changes/subapp-web/revert-cdnmapfix_2023-06-07-19-16.json
common/config/rush/pnpm-lock.yaml
packages/subapp-web/src/cdn-map.js
packages/xarc-webpack/src/client/webpack5-jsonp-cdn.ts

Reverting the fix added as part of https://github.com/electrode-io/electrode/pull/1972. This created other issues in case of subappv2. So parking this for further analysis

fix: revert cdn map fix previously added as this created other issues

---

common/changes/subapp-server/fix-missing-dependency_2023-10-26-21-33.json
common/config/rush/pnpm-lock.yaml
packages/subapp-server/package.json

- Fix missing `subapp-web` dependency in `subapp-server`
- Changelogs for the same

chore: fix missing dependency

---

common/changes/subapp-web/replace-ployfillurl_2024-07-03-15-06.json
packages/subapp-web/lib/polyfill.js

Update polyfill url to avoid security issue
For more info- https://www.sonatype.com/blog/polyfill.io-supply-chain-attack-hits-100000-websites-all-you-need-to-know

Replace polyfillurl to avoid security vulnerabilities

---

common/config/rush/pnpm-lock.yaml
docusaurus/docs/getting-started.md

Adding additional note for walmart developers

docs: update readme

---

common/changes/subapp-redux/fix-deprecated_createstore_2024-09-26-16-32.json
common/config/rush/pnpm-lock.yaml
packages/subapp-redux/package.json
packages/subapp-redux/src/index.jsx
packages/subapp-redux/src/shared.js
packages/subapp-redux/test/spec/index.spec.js
samples/poc-subapp-redux/package.json
samples/poc-subapp-redux/src/02.main-body/main-body.jsx
samples/poc-subapp-redux/src/04.footer/subapp-footer.jsx
samples/poc-subapp-redux/src/redux-store/actions/number-actions.js
samples/poc-subapp-redux/src/redux-store/reducers/number-reducer.js
samples/poc-subapp-redux/src/redux-store/reducers/root-reducer.js
samples/poc-subapp-redux/src/server-routes/default/index.js

createStore method from redux library is deprecated.Hence replace by configureStore from @reduxjs/toolkit library

Replace createStore by configureStore

---

common/config/rush/pnpm-lock.yaml
packages/subapp-web/package.json

Resolve issue while running v1 apps.

fix: v1 sample loading - Can't resolve 'url' issue

---

common/config/rush/pnpm-lock.yaml
packages/subapp-web/package.json
packages/xarc-react-router/tsconfig.browser.es2x.esm.json

Fix breaking of `rush update --full` command

fix: rush update --full command
